# Return On Investment Analysis

In [15]:
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import numpy_financial as npf

# Matplotlib darkmode
plt.style.use('dark_background')

# display settings
pd.set_option('display.max_columns', None)

## Load the model

In [16]:
model = joblib.load("../models/rental_price_model.pkl")

## Test model

Let's use a small test with preselected sale properties.

In [17]:
data = [
    {
        "link" : "https://www.property24.com/for-sale/arcadia/pretoria/gauteng/301/107631563",
        "location" : "Arcadia",
        "type" : "Apartment",
        "bedrooms" : 2.0,
        "bathrooms" : 2.0,
        "parking" : 1.0,
        "floor_size" : 64.0,
        "sale_price" : 1_250_000.00,
        "levies" : 1900.00,
        "rates_taxes" :950.00
    },
    {
        "link" : "https://www.property24.com/for-sale/arcadia/pretoria/gauteng/301/116702457",
        "location" : "Arcadia",
        "type" : "Apartment",
        "bedrooms" : 2.0,
        "bathrooms" : 1.0,
        "parking" : 1.0,
        "floor_size" : 78,
        "sale_price" : 550_000.00,
        "levies" : 2384.00,
        "rates_taxes" :389.00
    },
    {
        "link" : "i dont know",
        "location" : "Arcadia",
        "type" : "Apartment",
        "bedrooms" : 2.5,
        "bathrooms" : 2.0,
        "parking" : 1.0,
        "floor_size" : 88,
        "sale_price" : 525_000.00,
        "levies" : 1888.00,
        "rates_taxes" :434.00
    },
    {
        "link" : "https://www.property24.com/for-sale/brooklyn/pretoria/gauteng/614/116531184?plId=2243402&plt=3&plsIds=2263225",
        "location" : "Brooklyn",
        "type" : "Townhouse",
        "bedrooms" : 3.0,
        "bathrooms" : 3.5,
        "parking" : 2.0,
        "floor_size" : 350.0,
        "sale_price" : 2_350_000.00,
        "levies" : 2900.00,
        "rates_taxes" :2084.00
    },
    {
        "link" : "https://www.property24.com/to-rent/ashlea-gardens/pretoria/gauteng/235/116696639?uaid=40087192&utm_source=alert&utm_medium=email&utm_campaign=portalemailalerts",
        "location" : "Ashlea Gardens",
        "type" : "Townhouse",
        "bedrooms" : 3.0,
        "bathrooms" : 2.0,
        "parking" : 2.0,
        "floor_size" : 180.0,
        "sale_price" : 1_985_000.00,
        "levies" : 3063.00,
        "rates_taxes" :1123.00
    },
    {
        "link" : "https://www.property24.com/to-rent/ashlea-gardens/pretoria/gauteng/235/116696639?uaid=40087192&utm_source=alert&utm_medium=email&utm_campaign=portalemailalerts",
        "location" : "Ashlea Gardens",
        "type" : "Townhouse",
        "bedrooms" : 3.0,
        "bathrooms" : 2.5,
        "parking" : 4.0,
        "floor_size" : 230.0,
        "sale_price" : 3_385_000.00,
        "levies" : 3463.00,
        "rates_taxes" :1823.00
    },
]

test_df = pd.DataFrame(data)

In [18]:
test_df

,link,location,type,bedrooms,bathrooms,parking,floor_size,sale_price,levies,rates_taxes
0,https://www.property24.com/for-sale/arcadia/pr...,Arcadia,Apartment,2.0,2.0,1.0,64.0,1250000.0,1900.0,950.0
1,https://www.property24.com/for-sale/arcadia/pr...,Arcadia,Apartment,2.0,1.0,1.0,78.0,550000.0,2384.0,389.0
2,i dont know,Arcadia,Apartment,2.5,2.0,1.0,88.0,525000.0,1888.0,434.0
3,https://www.property24.com/for-sale/brooklyn/p...,Brooklyn,Townhouse,3.0,3.5,2.0,350.0,2350000.0,2900.0,2084.0
4,https://www.property24.com/to-rent/ashlea-gard...,Ashlea Gardens,Townhouse,3.0,2.0,2.0,180.0,1985000.0,3063.0,1123.0
5,https://www.property24.com/to-rent/ashlea-gard...,Ashlea Gardens,Townhouse,3.0,2.5,4.0,230.0,3385000.0,3463.0,1823.0

In [19]:
test_df['location'] = test_df['location'].astype('category')
test_df['type'] = test_df['type'].astype('category')

In [20]:
X = test_df.drop(columns=['link'])
X

,location,type,bedrooms,bathrooms,parking,floor_size,sale_price,levies,rates_taxes
0,Arcadia,Apartment,2.0,2.0,1.0,64.0,1250000.0,1900.0,950.0
1,Arcadia,Apartment,2.0,1.0,1.0,78.0,550000.0,2384.0,389.0
2,Arcadia,Apartment,2.5,2.0,1.0,88.0,525000.0,1888.0,434.0
3,Brooklyn,Townhouse,3.0,3.5,2.0,350.0,2350000.0,2900.0,2084.0
4,Ashlea Gardens,Townhouse,3.0,2.0,2.0,180.0,1985000.0,3063.0,1123.0
5,Ashlea Gardens,Townhouse,3.0,2.5,4.0,230.0,3385000.0,3463.0,1823.0

In [21]:
y_pred = model.predict(X)

In [22]:
y_pred = pd.DataFrame(y_pred, columns=['pred_rent'])
y_pred

      pred_rent
0  12292.494167
1   8161.979167
2   7937.783333
3  29993.666667
4  21265.133333
5  24867.500000

In [23]:
df = pd.merge(test_df,y_pred,left_index=True, right_index=True, how="inner")

In [24]:
df

,link,location,type,bedrooms,bathrooms,parking,floor_size,sale_price,levies,rates_taxes,pred_rent
0,https://www.property24.com/for-sale/arcadia/pr...,Arcadia,Apartment,2.0,2.0,1.0,64.0,1250000.0,1900.0,950.0,12292.494167
1,https://www.property24.com/for-sale/arcadia/pr...,Arcadia,Apartment,2.0,1.0,1.0,78.0,550000.0,2384.0,389.0,8161.979167
2,i dont know,Arcadia,Apartment,2.5,2.0,1.0,88.0,525000.0,1888.0,434.0,7937.783333
3,https://www.property24.com/for-sale/brooklyn/p...,Brooklyn,Townhouse,3.0,3.5,2.0,350.0,2350000.0,2900.0,2084.0,29993.666667
4,https://www.property24.com/to-rent/ashlea-gard...,Ashlea Gardens,Townhouse,3.0,2.0,2.0,180.0,1985000.0,3063.0,1123.0,21265.133333
5,https://www.property24.com/to-rent/ashlea-gard...,Ashlea Gardens,Townhouse,3.0,2.5,4.0,230.0,3385000.0,3463.0,1823.0,24867.500000

In [25]:
def calc_bond_payment(P, rate, years):
    r = rate / 12
    n = years * 12
    return npf.pmt(r, n, -P)

def calc_annual_rent(m_rent):
    return m_rent * 12

def calc_vacancy_loss(a_rent, loss_rate):
    return a_rent * loss_rate

def calc_monthly_expenses(levies, rates, maintenance = 0, insurance = 0, v_reserve = 0):
    return levies + rates + maintenance + insurance + v_reserve

def calc_annual_expenses(m_exps):
    return m_exps * 12

def calc_cashflow(m_rent, m_exps, m_mort):
    return m_rent - m_exps - m_mort

def calc_annual_cashflow(cashflow):
    return cashflow * 12

def calc_annual_noi(a_rent, a_exps):
    return a_rent - a_exps

def calc_cap_rate(a_noi, property_value):
    return a_noi / property_value * 100

def calc_roi(a_cashflow, property_price, closing_cost = 70000, reno_costs = 0):
    tot_investments = property_price + closing_cost + reno_costs
    return a_cashflow / tot_investments * 100

def calc_dscr(a_noi, m_mort):
    a_mort = m_mort * 12
    return a_noi / a_mort

def calc_expected_growth_rate(e_appr_rate, infla_rate):
    return e_appr_rate - infla_rate

def calc_break_even(a_exps, m_mort, a_rent):
    a_mort = m_mort * 12
    return (a_exps + a_mort) / a_rent

def calc_investment_score(cashflow, cap_rate, roi, dscr, inflation_adjusted_growth, break_even):
    
    # if cashflow < -(m_mort/2):
    #     cash_i = 0
    # elif cashflow > 3000:
    #     cash_i = 1
    # else:
    #     cash_i = (cashflow + (m_mort/2)) / (3000 + (m_mort/2))

    norm_cashflow = max(min(cashflow / 3000, 1), 0.0)
    norm_cap_rate = max(cap_rate, 0) / 12
    norm_roi = max(roi,0) / 20
    norm_dscr = min(max(dscr,0) / 1.5, 1)
    norm_growth = max((inflation_adjusted_growth + 5) / 10,0)
    norm_break_even = 1 - (break_even / 1.0)

    investment_score = (
        0.25 * norm_cashflow +
        0.20 * norm_cap_rate +
        0.20 * norm_roi +
        0.15 * norm_dscr +
        0.10 * norm_growth +
        0.10 * norm_break_even
    ) * 100

    return  max(min(investment_score, 100), 0)

In [26]:
calc_investment_score(-2400, -4, -2, -0.5, -6, 1.95)

0

In [27]:
df.loc[:, "monthly_repayments"] = df['sale_price'].apply(lambda x: calc_bond_payment(x,0.1025,20))

df.loc[:, "annual_rent"] = df['pred_rent'].apply(lambda x: calc_annual_rent(x))

df.loc[:, "vacancy_loss"] = df['annual_rent'].apply(lambda x: calc_vacancy_loss(x,0.07))

df.loc[:, "monthly_expenses"] = df.apply(lambda x: calc_monthly_expenses(x['levies'], x['rates_taxes']), axis=1)

df.loc[:, "annual_expenses"] = df["monthly_expenses"].apply(lambda x: calc_annual_expenses(x))

df.loc[:, "cashflow"] = df.apply(lambda x: calc_cashflow(x['pred_rent'], x['monthly_expenses'], x['monthly_repayments']), axis=1)

df.loc[:, "annual_cashflow"] = df['cashflow'].apply(lambda x: calc_annual_cashflow(x))

df.loc[:, "annual_noi"] = df.apply(lambda x: calc_annual_noi(x['annual_rent'], x['annual_expenses']) ,axis=1)

df.loc[:, "cap_rate"] = df.apply(lambda x: calc_cap_rate(x['annual_noi'], x['sale_price']),axis=1)

df.loc[:, "roi"] = df.apply(lambda x: calc_roi(x['annual_cashflow'], x['sale_price']),axis=1)

df.loc[:, "dscr"] = df.apply(lambda x: calc_dscr(x['annual_noi'],x['monthly_repayments']),axis=1)

df.loc[:, "growth"] = calc_expected_growth_rate(7,4)

df.loc[:, "break_even"] = df.apply(lambda x: calc_break_even(x['annual_expenses'], x['monthly_repayments'], x['annual_rent']),axis=1)

df.loc[:, 'score'] = df.apply(lambda x: calc_investment_score(x['cashflow'], x['cap_rate'], x['roi'], x['dscr'], x['growth'], x['break_even']),axis=1)

In [28]:
df.sort_values('score', ascending=False)

,link,location,type,bedrooms,bathrooms,parking,floor_size,sale_price,levies,rates_taxes,pred_rent,monthly_repayments,annual_rent,vacancy_loss,monthly_expenses,annual_expenses,cashflow,annual_cashflow,annual_noi,cap_rate,roi,dscr,growth,break_even,score
3,https://www.property24.com/for-sale/brooklyn/p...,Brooklyn,Townhouse,3.0,3.5,2.0,350.0,2350000.0,2900.0,2084.0,29993.666667,23068.619594,359924.00,25194.6800,4984.0,59808.0,1941.047072,23292.564870,300116.00,12.770894,0.962503,1.084142,3,0.935285,57.911293
2,i dont know,Arcadia,Apartment,2.5,2.0,1.0,88.0,525000.0,1888.0,434.0,7937.783333,5153.627782,95253.40,6667.7380,2322.0,27864.0,462.155552,5545.866620,67389.40,12.836076,0.932078,1.089676,3,0.941778,45.655815
1,https://www.property24.com/for-sale/arcadia/pr...,Arcadia,Apartment,2.0,1.0,1.0,78.0,550000.0,2384.0,389.0,8161.979167,5399.038628,97943.75,6856.0625,2773.0,33276.0,-10.059462,-120.713541,64667.75,11.757773,-0.019470,0.998137,3,1.001232,37.565331
4,https://www.property24.com/to-rent/ashlea-gard...,Ashlea Gardens,Townhouse,3.0,2.0,2.0,180.0,1985000.0,3063.0,1123.0,21265.133333,19485.621232,255181.60,17862.7120,4186.0,50232.0,-2406.487898,-28877.854780,204949.60,10.324917,-1.405248,0.876499,3,1.113166,32.841529
0,https://www.property24.com/for-sale/arcadia/pr...,Arcadia,Apartment,2.0,2.0,1.0,64.0,1250000.0,1900.0,950.0,12292.494167,12270.542337,147509.93,10325.6951,2850.0,34200.0,-2828.048171,-33936.578048,113309.93,9.064794,-2.570953,0.769525,3,1.230063,28.502615
5,https://www.property24.com/to-rent/ashlea-gard...,Ashlea Gardens,Townhouse,3.0,2.5,4.0,230.0,3385000.0,3463.0,1823.0,24867.500000,33228.628649,298410.00,20888.7000,5286.0,63432.0,-13647.128649,-163765.543794,234978.00,6.941743,-4.739958,0.589296,3,1.548794,19.974595