In [ ]:
import pandas as pd
import plotly.express as px
import geopandas as gpd
import plotly.graph_objects as go
import numpy as np
import osmnx as ox

In [2]:
import sys
print(sys.executable)

/home/tri_poloski/Documents/project-real-estate/venv/bin/python

In [3]:
import json

with open("../data/processed/gauteng_adm2.geojson") as f:
    gj = json.load(f)

# List of municipalities and colors
munis = ["City of Johannesburg", "City of Tshwane", "Ekurhuleni", "West Rand", "Sedibeng"]
colors = [25, 0, 0, 0, 0]

# Prepare DataFrame with one row per feature
data = []
for feat in gj["features"]:
    name = feat["properties"]["adm2_name"]
    # data.append({"municipality": name, "dummy": 1})
    color = colors[munis.index(name)] if name in munis else "lightgrey"  # color unmatched features grey
    data.append({"municipality": name, "color": color})

df = pd.DataFrame(data)
df["z"] = [1, 2, 3, 4, 5]
df

           municipality  color  z
0  City of Johannesburg     25  1
1       City of Tshwane      0  2
2            Ekurhuleni      0  3
3              Sedibeng      0  4
4             West Rand      0  5

In [4]:
df["municipality_clean"] = df["municipality"].str.strip().str.lower()
for feat in gj["features"]:
    feat["properties"]["adm2_name_clean"] = feat["properties"]["adm2_name"].strip().lower()

In [6]:
yield_df = pd.read_csv("../data/processed/yield.csv")

geo_df = gpd.GeoDataFrame.from_features(
    gj["features"]
).merge(yield_df, on="adm2_name").set_index("adm2_name")

fig = px.choropleth(geo_df,
                   geojson=geo_df.geometry,
                   locations=geo_df.index,
                   color="avg_yield",
                   projection="mercator")
fig.update_geos(fitbounds="locations", visible=False)
fig.show(renderer="browser")

In [25]:
df = pd.DataFrame({
    "state_code": ["AL", "AK", "AZ", "AR", "CA"],
    "value": [10, 20, 30, 40, 50]
})

fig = px.choropleth(
    df,
    locations="state_code",      # column with state codes
    locationmode="USA-states",   # tells Plotly these are 2-letter codes
    color="value",
    color_continuous_scale="Viridis",
    scope="usa",
)

fig.show(renderer="browser")

In [19]:
df = px.data.election()
geojson = px.data.election_geojson()

fig = px.choropleth(df, geojson=geojson, color="Bergeron",
                    locations="district", featureidkey="properties.district",
                    projection="mercator"
                   )
fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show(renderer="browser")

In [20]:
geojson

{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'geometry': {'type': 'MultiPolygon',
    'coordinates': [[[[-73.6363215300962, 45.5759177646435],
       [-73.6362833815582, 45.5758266113331],
       [-73.6446417578686, 45.5658132919643],
       [-73.6453511352974, 45.5647725775888],
       [-73.648867564748, 45.5586898267402],
       [-73.6513170845065, 45.5545659435652],
       [-73.6515658357324, 45.5554439857955],
       [-73.6660837831645, 45.5596724837829],
       [-73.6706609041685, 45.5610978251999],
       [-73.6676019919116, 45.5632340862888],
       [-73.6645385824068, 45.5642716484367],
       [-73.663663123697, 45.5654269638586],
       [-73.663336397858, 45.5666288247853],
       [-73.6637764768649, 45.5678900619231],
       [-73.6625073244826, 45.5688479494114],
       [-73.6624620526633, 45.5708304456346],
       [-73.6620201425015, 45.5713925326191],
       [-73.6616100197742, 45.5737924780218],
       [-73.6612199500215, 45.5747171555678],
       [-73.6625087613399, 45.5748980132699],
       [-73.6639172423219, 45.5730041908097],
       [-73.6654358660443, 45.5729040009532],
       [-73.6661069174428, 45.5737928224235],
       [-73.6657870687343, 45.574385118162],
       [-73.6636711124334, 45.577018676761],
       [-73.6620928771361, 45.578161887933],
       [-73.6611738698168, 45.5798517041392],
       [-73.660404649744, 45.5806752214364],
       [-73.659760079306, 45.5804007503503],
       [-73.6604711314507, 45.5793767269523],
       [-73.660479658497, 45.5787710701802],
       [-73.6613549575147, 45.5780184952852],
       [-73.6617871566128, 45.5758213640561],
       [-73.6607445476436, 45.5764832852254],
       [-73.6608243059909, 45.5774702934068],
       [-73.6592236423267, 45.5793785624903],
       [-73.6570262958283, 45.5810509513563],
       [-73.6552694168748, 45.5819333817794],
       [-73.6543058972308, 45.5836262624158],
       [-73.652557313063, 45.5826892716542],
       [-73.6363215300962, 45.5759177646435]]],
     [[[-73.6561004885273, 45.5841347974261],
       [-73.656376117147, 45.5845383929424],
       [-73.6559939844354, 45.585868003125],
       [-73.6552168328229, 45.5855392416017],
       [-73.6561004885273, 45.5841347974261]]]]},
   'properties': {'district': '11-Sault-au-Récollet'},
   'id': '11'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.6217484540132, 45.5544783077209],
      [-73.6235005117779, 45.5536358848324],
      [-73.6278096771011, 45.5513024018691],
      [-73.6301686544477, 45.5503989164938],
      [-73.6325600663803, 45.5499795021129],
      [-73.6342899238824, 45.5494628161417],
      [-73.6363671046978, 45.548169415833],
      [-73.6398673671325, 45.5441488267699],
      [-73.6407295659042, 45.5429686686779],
      [-73.6485543103777, 45.5308320827376],
      [-73.6510270564502, 45.5263874543882],
      [-73.6555330494037, 45.5277342274232],
      [-73.6698852350516, 45.5318835785726],
      [-73.6726124365382, 45.5322997327559],
      [-73.6747555535799, 45.5323081056009],
      [-73.6764129283619, 45.5321264506516],
      [-73.683124268159, 45.5305991300384],
      [-73.6807721370907, 45.534331320177],
      [-73.6785046215606, 45.5379069417581],
      [-73.6752852955733, 45.5369404343695],
      [-73.6740837310465, 45.5378868187786],
      [-73.6687347480061, 45.5363337408676],
      [-73.667891862525, 45.5387409623539],
      [-73.664945183105, 45.5382590909533],
      [-73.6646235398403, 45.5394847807605],
      [-73.662249203322, 45.543633408253],
      [-73.6616100449503, 45.5441416421638],
      [-73.6604302515405, 45.5460790656787],
      [-73.6568659704249, 45.5450525873044],
      [-73.6513170845065, 45.5545659435652],
      [-73.648867564748, 45.5586898267402],
      [-73.6453511352974, 45.5647725775888],
      [-73.6240413737876, 45.5555253903511],
      [-73.6217484540132, 45.5544783077209]]]},
   'properties': {'district': '12-Saint-Sulpice'},
   'id': '12'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.6513170845065, 45.5545659435652],
      [-73.6568659704249, 45.5450525873044],
      [-73.6604302515405, 45.5460790656787],
      [-73.6616100449503, 45.5441416421638],
      [-73.662249203322, 45.543633408253],
      [-73.6646235398403, 45.5394847807605],
      [-73.664945183105, 45.5382590909533],
      [-73.667891862525, 45.5387409623539],
      [-73.6687347480061, 45.5363337408676],
      [-73.6740837310465, 45.5378868187786],
      [-73.6752852955733, 45.5369404343695],
      [-73.6785046215606, 45.5379069417581],
      [-73.6807721370907, 45.534331320177],
      [-73.6920199187781, 45.5394683031028],
      [-73.702520410412, 45.5431766227664],
      [-73.7042065154565, 45.5438906316964],
      [-73.7043014929187, 45.5441905861876],
      [-73.7027027602765, 45.5451406840713],
      [-73.7023335988111, 45.5457621950639],
      [-73.7012226911876, 45.5459702396396],
      [-73.7004635154173, 45.5466167282154],
      [-73.6996123824321, 45.5464852570484],
      [-73.6992033294858, 45.5475781625301],
      [-73.6968595536907, 45.5481581755357],
      [-73.6949311086011, 45.5474604427764],
      [-73.6924688517172, 45.5472280284581],
      [-73.6891281157722, 45.5477334249253],
      [-73.6879273316976, 45.5481318231022],
      [-73.6865595013798, 45.5491308196528],
      [-73.6852748086046, 45.5488162600605],
      [-73.6827845213391, 45.5489146412483],
      [-73.6801283681886, 45.549462773374],
      [-73.6791182211476, 45.5500801562043],
      [-73.6772981030339, 45.5516675115113],
      [-73.6765545558035, 45.552766523393],
      [-73.6744642269172, 45.5548591969672],
      [-73.6730096784532, 45.5582339830541],
      [-73.6706609041685, 45.5610978251999],
      [-73.6660837831645, 45.5596724837829],
      [-73.6515658357324, 45.5554439857955],
      [-73.6513170845065, 45.5545659435652]]]},
   'properties': {'district': '13-Ahuntsic'},
   'id': '13'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.7043014929187, 45.5441905861876],
      [-73.7042065154565, 45.5438906316964],
      [-73.702520410412, 45.5431766227664],
      [-73.6920199187781, 45.5394683031028],
      [-73.6807721370907, 45.534331320177],
      [-73.683124268159, 45.5305991300384],
      [-73.685195685208, 45.5301022578388],
      [-73.6870922504792, 45.5286619976995],
      [-73.6897803429098, 45.5288476157777],
      [-73.6939612003867, 45.528347826243],
      [-73.6963296087078, 45.5276805484038],
      [-73.7091218538247, 45.5230954877394],
      [-73.7112612170074, 45.5243023856458],
      [-73.7131122096208, 45.5251637887575],
      [-73.7145584630039, 45.5239315629596],
      [-73.7172924358234, 45.5256928911099],
      [-73.7185119695016, 45.5247508136954],
      [-73.7217031155859, 45.5267447688191],
      [-73.7280602953464, 45.5213554616816],
      [-73.7317546325275, 45.5236815365784],
      [-73.7358987648866, 45.5207291683311],
      [-73.7285097856203, 45.5160943522463],
      [-73.7350991221023, 45.5137867482303],
      [-73.7550630650544, 45.5065238038199],
      [-73.7551669017747, 45.5064862077527],
      [-73.7612752776246, 45.5104175090183],
      [-73.7638683329059, 45.5120860463668],
      [-73.762390301954, 45.5126791739444],
      [-73.7600609683013, 45.5141288858482],
      [-73.7568442082942, 45.5171884494623],
      [-73.7548593171474, 45.5180889539846],
      [-73.752606980088, 45.5185523798859],
      [-73.749151955166, 45.519018390863],
      [-73.7452110015187, 45.5215286261207],
      [-73.7437662661847, 45.5231373686573],
      [-73.7411211602605, 45.526837900694],
      [-73.7394306858002, 45.5285277381045],
      [-73.7360589393138, 45.5302671129156],
      [-73.7343347000828, 45.5309824138834],
      [-73.7311072638005, 45.5320095049916],
      [-73.7283844986554, 45.533203827821],
      [-73.7249729419404, 45.5359178137401],
      [-73.7231098233772, 45.5369689627545],
      [-73.7202103870331, 45.5381794076214],
      [-73.7181375140605, 45.5387109207903],
      [-73.7158043157039, 45.5388996570908],
      [-73.7135388429561, 45.5396848689224],
      [-73.7111454931799, 45.541340948266],
      [-73.7091038651233, 45.5430898357363],
      [-73.7078456046825, 45.5423008892929],
      [-73.7069875096913, 45.5436077713277],
      [-73.705614345008, 45.5441267025504],
      [-73.7043014929187, 45.5441905861876]]]},
   'properties': {'district': '14-Bordeaux-Cartierville'},
   'id': '14'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.5576871015794, 45.5932166140624],
      [-73.5694206600629, 45.5971486400825],
      [-73.5696609688417, 45.5965806032278],
      [-73.5726733802096, 45.5977479911912],
      [-73.5745938220503, 45.5986717630315],
      [-73.576232424293, 45.5992577290381],
      [-73.5771288919308, 45.599852413767],
      [-73.5889961999073, 45.6050220349527],
      [-73.5971103983983, 45.6085989887758],
      [-73.6013378366857, 45.6104025414741],
      [-73.6028907661658, 45.6112216102358],
      [-73.601559767966, 45.6118073578371],
      [-73.6023660828945, 45.6125718329314],
      [-73.5984976040034, 45.6140840514745],
      [-73.5954830428467, 45.6158123480652],
      [-73.5740068269183, 45.6304929149516],
      [-73.5683379250343, 45.6341956640577],
      [-73.5514095863784, 45.6269444197056],
      [-73.5481773494253, 45.6255197854529],
      [-73.5585223912755, 45.6137280036474],
      [-73.5640615699407, 45.6074316710882],
      [-73.564986439275, 45.60561620283],
      [-73.5662995431109, 45.6039974029119],
      [-73.5631517029922, 45.6031634368599],
      [-73.5614050931716, 45.6025489377902],
      [-73.5567925816714, 45.6005393547562],
      [-73.5589887922886, 45.5979945383903],
      [-73.5595164040348, 45.5961661000645],
      [-73.5564557704867, 45.5951543577536],
      [-73.5576871015794, 45.5932166140624]]]},
   'properties': {'district': '21-Ouest'},
   'id': '21'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.5452799498143, 45.5959627917351],
      [-73.5491007054645, 45.5975302159963],
      [-73.5479841638628, 45.5989434662401],
      [-73.5468145864499, 45.6013644519429],
      [-73.5461968110206, 45.6046211322422],
      [-73.549913736884, 45.605150517886],
      [-73.5533688744189, 45.605412630486],
      [-73.5524302953106, 45.6080081462088],
      [-73.5507759763854, 45.6103339985918],
      [-73.5585223912755, 45.6137280036474],
      [-73.5481773494253, 45.6255197854529],
      [-73.5358870172169, 45.620207093019],
      [-73.5374747721378, 45.6166252950092],
      [-73.5375256945614, 45.6160673327401],
      [-73.5381703589619, 45.6139517855176],
      [-73.5437218072693, 45.6149096422408],
      [-73.5452777806501, 45.6141657083913],
      [-73.5462767505068, 45.6127238289344],
      [-73.5444977198785, 45.6121760838565],
      [-73.5453373826653, 45.6107633861198],
      [-73.5441363974969, 45.6102716461918],
      [-73.5412098839782, 45.6095033241271],
      [-73.5416434070878, 45.6081797015109],
      [-73.540900931842, 45.6078533012629],
      [-73.5416213388458, 45.606939681157],
      [-73.5375401492111, 45.6052359766051],
      [-73.5365038947396, 45.6026457300995],
      [-73.5365958888719, 45.602162446611],
      [-73.5394321608651, 45.6030910243993],
      [-73.5421763850909, 45.6042454438226],
      [-73.5429289535666, 45.6032316351511],
      [-73.539729971205, 45.6018186221009],
      [-73.5407418924341, 45.6006998521118],
      [-73.5447576674512, 45.6019410417126],
      [-73.5451108447268, 45.6000061818095],
      [-73.5445859643042, 45.5999308464328],
      [-73.5442050076359, 45.5981948225546],
      [-73.5438572127564, 45.5980784963673],
      [-73.5452799498143, 45.5959627917351]]]},
   'properties': {'district': '22-Est'},
   'id': '22'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.5576871015794, 45.5932166140624],
      [-73.5564557704867, 45.5951543577536],
      [-73.5595164040348, 45.5961661000645],
      [-73.5589887922886, 45.5979945383903],
      [-73.5567925816714, 45.6005393547562],
      [-73.5614050931716, 45.6025489377902],
      [-73.5631517029922, 45.6031634368599],
      [-73.5662995431109, 45.6039974029119],
      [-73.564986439275, 45.60561620283],
      [-73.5640615699407, 45.6074316710882],
      [-73.5585223912755, 45.6137280036474],
      [-73.5507759763854, 45.6103339985918],
      [-73.5524302953106, 45.6080081462088],
      [-73.5533688744189, 45.605412630486],
      [-73.549913736884, 45.605150517886],
      [-73.5461968110206, 45.6046211322422],
      [-73.5468145864499, 45.6013644519429],
      [-73.5479841638628, 45.5989434662401],
      [-73.5491007054645, 45.5975302159963],
      [-73.5452799498143, 45.5959627917351],
      [-73.5455045323429, 45.5956272275911],
      [-73.545930102715, 45.5949937733284],
      [-73.5473484500099, 45.5955355370728],
      [-73.5481396292151, 45.5946360429193],
      [-73.5465394629102, 45.5940712033384],
      [-73.5489394765731, 45.5903029802044],
      [-73.5576871015794, 45.5932166140624]]]},
   'properties': {'district': '23-Centre'},
   'id': '23'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.6207592308166, 45.5138993727882],
      [-73.6236560898078, 45.5106541632808],
      [-73.624384898555, 45.5091582170891],
      [-73.6260875230251, 45.507277208983],
      [-73.6279506225702, 45.5061120243158],
      [-73.628749836468, 45.5048079525531],
      [-73.6304494685866, 45.5028490467289],
      [-73.6256440443835, 45.500662130816],
      [-73.6331323407225, 45.49234917306],
      [-73.6480439724158, 45.4990451424615],
      [-73.6458072174417, 45.5016289991394],
      [-73.6422399591459, 45.5054987858353],
      [-73.6423036889254, 45.5062221151428],
      [-73.6415508188144, 45.5069829054595],
      [-73.6416660769228, 45.5076101030023],
      [-73.6385805807369, 45.5112159439382],
      [-73.6365911851412, 45.5146566965285],
      [-73.6357295158589, 45.5143963845137],
      [-73.6346269691423, 45.5156528191911],
      [-73.6289040380069, 45.5140823858644],
      [-73.6267223236567, 45.5165801475772],
      [-73.6207592308166, 45.5138993727882]]]},
   'properties': {'district': '31-Darlington'},
   'id': '31'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.5956108742759, 45.504064067218],
      [-73.5941401789655, 45.5033436344744],
      [-73.594737745289, 45.5028667176493],
      [-73.5977240363362, 45.5016310280474],
      [-73.5997960499359, 45.5001439911523],
      [-73.6009279740317, 45.4988800346583],
      [-73.6033750499038, 45.4967309718248],
      [-73.6044775189475, 45.4952226776326],
      [-73.6068399722065, 45.4952769144878],
      [-73.6083680626652, 45.493592693099],
      [-73.6093606035265, 45.4939788081012],
      [-73.6115925457235, 45.4916920833656],
      [-73.6147351668377, 45.4930299583055],
      [-73.6184160919695, 45.4889467204633],
      [-73.618423454854, 45.4881800607925],
      [-73.6153515138627, 45.4867956883177],
      [-73.6169038962737, 45.4851011880198],
      [-73.6331323407225, 45.49234917306],
      [-73.6256440443835, 45.500662130816],
      [-73.6304494685866, 45.5028490467289],
      [-73.628749836468, 45.5048079525531],
      [-73.6279506225702, 45.5061120243158],
      [-73.6260875230251, 45.507277208983],
      [-73.624384898555, 45.5091582170891],
      [-73.6236560898078, 45.5106541632808],
      [-73.6207592308166, 45.5138993727882],
      [-73.6176645335398, 45.5125000231349],
      [-73.617959519301, 45.5121686212918],
      [-73.61888001694, 45.5111346532789],
      [-73.6169256431203, 45.5102737338336],
      [-73.6178928803835, 45.5091750557282],
      [-73.6160933747766, 45.5082725969653],
      [-73.6189454361275, 45.5051234940594],
      [-73.6182356279483, 45.504722156916],
      [-73.6130513861854, 45.5104478685544],
      [-73.6063535452531, 45.5074911306599],
      [-73.6061344132343, 45.5068772235294],
      [-73.6035337540631, 45.5057001623398],
      [-73.6024762927983, 45.5068574351344],
      [-73.5993805679324, 45.5053898653966],
      [-73.5987846893921, 45.5056180649425],
      [-73.5956108742759, 45.504064067218]]]},
   'properties': {'district': '32-Côte-des-Neiges'},
   'id': '32'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.6458072174417, 45.5016289991394],
      [-73.6480439724158, 45.4990451424615],
      [-73.6331323407225, 45.49234917306],
      [-73.6169038962737, 45.4851011880198],
      [-73.6171481421592, 45.4848346166979],
      [-73.6143642141962, 45.4835868912093],
      [-73.6159143530659, 45.4828328944331],
      [-73.6178740199084, 45.4828487105026],
      [-73.6188871149392, 45.4826094451865],
      [-73.6212759199926, 45.4802684345737],
      [-73.6225662166532, 45.4809098124242],
      [-73.6236079242847, 45.479859834089],
      [-73.6247644644914, 45.4792722536745],
      [-73.6274376104247, 45.4787022686984],
      [-73.6296262215988, 45.478422071886],
      [-73.6309839979771, 45.4790336481084],
      [-73.6303804074798, 45.4796761714723],
      [-73.6511475576679, 45.4890232837666],
      [-73.6486185977978, 45.4918874029923],
      [-73.6505027283703, 45.4926843456098],
      [-73.6558244313911, 45.4867907549359],
      [-73.6554964724779, 45.4865593791057],
      [-73.6559518311015, 45.4851214751334],
      [-73.6560231568666, 45.4789400952457],
      [-73.6611067166692, 45.4811529055447],
      [-73.6618618884249, 45.4803203895973],
      [-73.6695855765435, 45.483802365291],
      [-73.6746342471328, 45.4819683440264],
      [-73.6763145414839, 45.4831298265322],
      [-73.6776271543493, 45.4823345919293],
      [-73.677264286648, 45.4836591822082],
      [-73.6751680903633, 45.4912833590877],
      [-73.6678730495106, 45.4869534898132],
      [-73.6660964808822, 45.4866186123515],
      [-73.665349200462, 45.4870183659149],
      [-73.6562276688947, 45.49432722353],
      [-73.6637510731136, 45.4992450684359],
      [-73.6617471598017, 45.4992191258018],
      [-73.6623623016746, 45.5022066512214],
      [-73.6605369493135, 45.5024306141327],
      [-73.6600841825714, 45.50331916613],
      [-73.659999506549, 45.5047080114556],
      [-73.6566453499119, 45.5037588241059],
      [-73.6516126661051, 45.504311872331],
      [-73.6458072174417, 45.5016289991394]]]},
   'properties': {'district': '33-Snowdon'},
   'id': '33'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.6143642141962, 45.4835868912093],
      [-73.6123997707291, 45.4826898974257],
      [-73.6143764334436, 45.4805885224868],
      [-73.6054346259738, 45.4765925587108],
      [-73.605024536716, 45.4770080719998],
      [-73.5985471562789, 45.4740708829885],
      [-73.5951347718664, 45.4764466331536],
      [-73.5966486659517, 45.4732210790839],
      [-73.5995923966142, 45.4714885118876],
      [-73.6015380888098, 45.4698449656495],
      [-73.6025897276388, 45.4690525247808],
      [-73.6031619796725, 45.4691032161751],
      [-73.6056266168094, 45.4676031109374],
      [-73.6058459619009, 45.4672881102352],
      [-73.6116004847967, 45.4647691120724],
      [-73.6121904900053, 45.4648542087469],
      [-73.6157015928197, 45.4632907897894],
      [-73.6167538282606, 45.4637150194085],
      [-73.6260868871444, 45.4678594502274],
      [-73.626514031426, 45.4682540051731],
      [-73.6317531402478, 45.4705324186308],
      [-73.6328791824832, 45.4692477650227],
      [-73.6375349663401, 45.4712784001916],
      [-73.636638362928, 45.4717833758261],
      [-73.6429334550997, 45.4745543212637],
      [-73.6397624769414, 45.4766952953752],
      [-73.6393702983563, 45.4768105158646],
      [-73.6354876412699, 45.4768957315274],
      [-73.6324931664858, 45.477871983287],
      [-73.6296262215988, 45.478422071886],
      [-73.6274376104247, 45.4787022686984],
      [-73.6247644644914, 45.4792722536745],

In [38]:
gj['features'][2]['properties']

{'adm2_name': 'Ekurhuleni'}

In [37]:
geojson['features'][0]['properties']

{'district': '11-Sault-au-Récollet'}

In [17]:
gdf = gpd.read_file("../data/zaf_admin_boundaries.geojson/zaf_admin2.geojson")

In [18]:
gdf[gdf['adm1_name'] == 'Gauteng']

,adm2_name,adm2_name1,adm2_name2,adm2_name3,adm2_pcode,adm1_name,adm1_name1,adm1_name2,adm1_name3,adm1_pcode,...,area_sqkm,version,lang,lang1,lang2,lang3,adm2_ref_name,center_lat,center_lon,geometry
11,City of Johannesburg,JHB,None,None,ZA798,Gauteng,GT,None,None,ZA7,...,1644.931094,v01,en,id,None,None,City of Johannesburg,-26.214795,27.919478,"POLYGON ((27.98484 -25.90973, 27.98476 -25.909..."
12,City of Tshwane,TSH,None,None,ZA799,Gauteng,GT,None,None,ZA7,...,6297.834912,v01,en,id,None,None,City of Tshwane,-25.593968,28.302789,"POLYGON ((28.75833 -25.14728, 28.75774 -25.145..."
17,Ekurhuleni,EKU,None,None,ZA797,Gauteng,GT,None,None,ZA7,...,1975.358175,v01,en,id,None,None,Ekurhuleni,-26.184765,28.321073,"POLYGON ((28.25658 -25.92406, 28.24464 -25.923..."
35,Sedibeng,DC42,None,None,ZA742,Gauteng,GT,None,None,ZA7,...,4172.761291,v01,en,id,None,None,Sedibeng,-26.547940,28.101508,"POLYGON ((28.67521 -26.32227, 28.67487 -26.322..."
48,West Rand,DC48,None,None,ZA748,Gauteng,GT,None,None,ZA7,...,4087.422629,v01,en,id,None,None,West Rand,-26.223139,27.513102,"POLYGON ((27.64355 -25.79592, 27.64207 -25.796..."

In [36]:
gauteng_munis = gdf[gdf['adm1_name']=='Gauteng'].copy()

# Keep only what you need
gauteng_munis = gauteng_munis[["adm2_name", "geometry"]]
# gauteng_munis = gauteng_munis.to_crs(epsg=4326)

g_df = gpd.GeoDataFrame.from_features(
    json.loads(gauteng_munis.to_json())["features"]
).merge(yield_df, on="adm2_name").set_index("adm2_name")

fig = px.choropleth(g_df,
                   geojson=g_df.geometry,
                   locations=g_df.index,
                   color="avg_yield",
                   projection="mercator")
fig.update_geos(fitbounds="locations", visible=False)
fig.show(renderer="browser")

# Convert to WGS84 (EPSG:4326)
# gauteng_munis = gauteng_munis.to_crs(epsg=4326)

# Save
# gauteng_munis.to_file("../data/processed/gauteng_adm2.geojson", driver="GeoJSON")

In [37]:
# Load GeoJSON
with open("../data/gauteng_province.geojson") as f:
    gauteng_geojson = json.load(f)

In [47]:
gauteng_geojson['features'][0]['geometry']

{'type': 'Polygon',
 'coordinates': [[[27.15634, -26.52431],
   [27.15876, -26.52542],
   [27.15878, -26.52553],
   [27.16068, -26.5315],
   [27.16247, -26.53699],
   [27.16386, -26.54141],
   [27.16423, -26.54248],
   [27.16679, -26.55052],
   [27.1671, -26.55143],
   [27.1701, -26.55053],
   [27.17455, -26.54921],
   [27.17467, -26.54943],
   [27.17531, -26.55053],
   [27.17843, -26.55592],
   [27.17888, -26.5567],
   [27.18046, -26.55946],
   [27.1809, -26.56018],
   [27.18093, -26.56029],
   [27.18128, -26.56092],
   [27.18131, -26.56092],
   [27.18148, -26.56122],
   [27.18183, -26.56183],
   [27.18256, -26.56313],
   [27.18261, -26.56345],
   [27.18259, -26.56524],
   [27.1826, -26.56835],
   [27.18262, -26.57028],
   [27.18263, -26.5711],
   [27.18263, -26.57188],
   [27.18262, -26.57273],
   [27.18264, -26.57347],
   [27.18265, -26.57422],
   [27.182642, -26.574554],
   [27.182637, -26.57462],
   [27.19547, -26.57361],
   [27.19967, -26.57328],
   [27.2226586, -26.5714334],
   [27.22836, -26.57105],
   [27.22919, -26.57431],
   [27.2295, -26.57552],
   [27.23003, -26.57755],
   [27.23019, -26.57813],
   [27.23165, -26.58383],
   [27.23369, -26.59162],
   [27.23452, -26.59492],
   [27.23321, -26.59546],
   [27.2336, -26.60052],
   [27.23376, -26.60265],
   [27.23378, -26.6029],
   [27.23379, -26.60335],
   [27.23502, -26.61862],
   [27.23767, -26.6255],
   [27.23835, -26.62744],
   [27.23839, -26.62756],
   [27.2388, -26.62857],
   [27.23888, -26.62875],
   [27.23893, -26.62897],
   [27.24164, -26.63589],
   [27.24187, -26.63646],
   [27.24194, -26.6364],
   [27.24209, -26.63621],
   [27.24225, -26.63601],
   [27.24243, -26.63597],
   [27.24274, -26.6359],
   [27.2432, -26.63582],
   [27.24365, -26.63573],
   [27.24392, -26.6356],
   [27.24407, -26.63533],
   [27.24428, -26.63511],
   [27.24446, -26.63502],
   [27.24484, -26.63502],
   [27.24532, -26.6351],
   [27.24549, -26.63514],
   [27.2456, -26.63514],
   [27.24583, -26.63507],
   [27.24595, -26.63502],
   [27.2461, -26.63487],
   [27.24642, -26.63472],
   [27.24661, -26.63472],
   [27.24698, -26.63464],
   [27.24717, -26.63449],
   [27.24743, -26.63437],
   [27.24782, -26.63437],
   [27.24812, -26.63453],
   [27.2482, -26.63476],
   [27.24812, -26.63516],
   [27.24789, -26.63544],
   [27.24776, -26.63565],
   [27.24772, -26.63587],
   [27.24781, -26.63603],
   [27.24796, -26.63609],
   [27.24816, -26.63607],
   [27.24854, -26.63613],
   [27.24885, -26.63605],
   [27.2488859, -26.636001],
   [27.24896, -26.6359],
   [27.24902, -26.63556],
   [27.24907, -26.63521],
   [27.2491146, -26.6348758],
   [27.24913, -26.63476],
   [27.2492, -26.63448],
   [27.24927, -26.63422],
   [27.24938, -26.63406],
   [27.24956, -26.63405],
   [27.24967, -26.63418],
   [27.24967, -26.6344682],
   [27.24967, -26.63487],
   [27.2497, -26.63495],
   [27.25009, -26.63479],
   [27.25034, -26.63464],
   [27.25058, -26.6346],
   [27.25104, -26.63472],
   [27.25125, -26.6347],
   [27.25137, -26.63458],
   [27.25133, -26.63435],
   [27.2511, -26.6342],
   [27.25079, -26.63405],
   [27.25079, -26.63392],
   [27.25089, -26.63384],
   [27.25134, -26.63382],
   [27.25204, -26.6338],
   [27.25216, -26.6338],
   [27.25249, -26.63363],
   [27.25268, -26.6334],
   [27.2528, -26.63306],
   [27.25289, -26.63291],
   [27.25312, -26.63279],
   [27.25341, -26.6327],
   [27.25369, -26.63248],
   [27.25387, -26.63242],
   [27.25448, -26.63221],
   [27.25497, -26.63218],
   [27.25546, -26.63227],
   [27.25598, -26.63242],
   [27.25628, -26.63244],
   [27.25656, -26.63245],
   [27.25677, -26.6323],
   [27.25686, -26.63212],
   [27.25687, -26.63204],
   [27.25701, -26.63198],
   [27.25728, -26.63201],
   [27.25753, -26.63201],
   [27.25771, -26.63186],
   [27.25777, -26.63174],
   [27.25774, -26.63152],
   [27.25756, -26.63143],
   [27.25744, -26.63131],
   [27.25728, -26.63129],
   [27.25713, -26.63117],
   [27.25713, -26.631],
   [27.25722, -26.63085],
   [27.25738, -26.63082],
   [27.25802, -26.63086],
   [27.25838, -26.63091],
   [27.25878, -26.631],
   [27.2593, -26.63106],
   [27.25997, -26.63119],
   [27.26049, -26.63149],
   [27.26077, -26.63167],
   [27.26095, -26.63189],
   [27.26107, -26.63219],
   [27.26113, -26.63244],
   [27.26122, -26.63262],
   [27.26141, -26.63271],
   [27.26156, -26.63277],
   [27.26162, -26.63296],
   [27.26161, -26.63307],
   [27.26147, -26.63314],
   [27.26144, -26.6332],
   [27.26147, -26.63345],
   [27.26168, -26.63354],
   [27.26217, -26.63351],
   [27.26251, -26.63338],
   [27.26263, -26.63317],
   [27.26266, -26.63279],
   [27.26273, -26.63261],
   [27.26297, -26.6325],
   [27.26346, -26.63241],
   [27.26395, -26.63222],
   [27.26411, -26.63208],
   [27.2642, -26.63183],
   [27.26429, -26.63171],
   [27.26444, -26.63167],
   [27.26462, -26.63171],
   [27.26481, -26.63195],
   [27.26496, -26.63207],
   [27.26508, -26.63216],
   [27.26529, -26.63232],
   [27.26545, -26.6325],
   [27.26569, -26.63249],
   [27.26581, -26.63219],
   [27.26592, -26.63201],
   [27.266, -26.63183],
   [27.26604, -26.63163],
   [27.26629, -26.63141],
   [27.26653, -26.63132],
   [27.26687, -26.6312],
   [27.26693, -26.63111],
   [27.26696, -26.63083],
   [27.26693, -26.6307],
   [27.26693, -26.63059],
   [27.26714, -26.63056],
   [27.26742, -26.63068],
   [27.26766, -26.6309],
   [27.26772, -26.63117],
   [27.26766, -26.63138],
   [27.26763, -26.63157],
   [27.26745, -26.63178],
   [27.26734, -26.63193],
   [27.26734, -26.63236],
   [27.26746, -26.63248],
   [27.26778, -26.63264],
   [27.268, -26.63267],
   [27.26806, -26.63268],
   [27.26826, -26.63287],
   [27.26866, -26.63287],
   [27.26914, -26.63274],
   [27.26928, -26.63266],
   [27.2694, -26.63262],
   [27.26973, -26.63241],
   [27.26994, -26.63225],
   [27.27001, -26.63222],
   [27.27013, -26.63212],
   [27.27026, -26.63198],
   [27.27037, -26.63174],
   [27.27046, -26.63152],
   [27.27059, -26.63137],
   [27.27086, -26.63122],
   [27.27118, -26.63112],
   [27.27138, -26.631],
   [27.2715, -26.63073],
   [27.27159, -26.63045],
   [27.27176, -26.63039],
   [27.27193, -26.63039],
   [27.27205, -26.63045],
   [27.27224, -26.63073],
   [27.27233, -26.63079],
   [27.27269, -26.63082],
   [27.27282, -26.63088],
   [27.27282, -26.63094],
   [27.27275, -26.63106],
   [27.27233, -26.63131],
   [27.27234, -26.63134],
   [27.27231, -26.63135],
   [27.27227, -26.63143],
   [27.27227, -26.63152],
   [27.27236, -26.63163],
   [27.2726, -26.63174],
   [27.2727, -26.63179],
   [27.27278, -26.63188],
   [27.27286, -26.63205],
   [27.27293, -26.63217],
   [27.273, -26.63219],
   [27.27307, -26.63218],
   [27.27317, -26.63209],
   [27.27331, -26.63194],
   [27.27353, -26.63177],
   [27.27368, -26.6316],
   [27.27386, -26.63135],
   [27.27403, -26.63124],
   [27.27418, -26.63118],
   [27.27436, -26.6311],
   [27.27452, -26.631],
   [27.27464, -26.63085],
   [27.27466, -26.63068],
   [27.27464, -26.63052],
   [27.2746, -26.63043],
   [27.2745, -26.63026],
   [27.27443, -26.63002],
   [27.27443, -26.62995],
   [27.27448, -26.62985],
   [27.27457, -26.62978],
   [27.27473, -26.6297],
   [27.27489, -26.62968],
   [27.27547, -26.62967],
   [27.27572, -26.62964],
   [27.27586, -26.62961],
   [27.27608, -26.62955],
   [27.27625, -26.62947],
   [27.27656, -26.62927],
   [27.27674, -26.62914],
   [27.27688, -26.629],
   [27.27699, -26.62878],
   [27.27712, -26.62851],
   [27.27725, -26.62825],
   [27.27732, -26.62801],
   [27.27732, -26.62787],
   [27.27728, -26.62769],
   [27.27728, -26.6275],
   [27.2773, -26.62728],
   [27.27731, -26.62711],
   [27.27734, -26.62689],
   [27.27733, -26.62682],
   [27.27729, -26.62673],
   [27.27707, -26.62664],
   [27.27702, -26.6266],
   [27.27699, -26.62653],
   [27.27699, -26.62638],
   [27.27692, -26.62626],
   [27.27685, -26.62616],
   [27.27681, -26.62608],
   [27.27682, -26.626],
   [27.27684, -26.62592],
   [27.27694, -26.62585],
   [27.27707, -26.62585],
   [27.27719, -26.6259],
   [27.27737, -26.62607],
   [27.2776, -26.62631],
   [27.27769, -26.6264],
   [27.2778, -26.62647],
   [27.27832, -26.62653],
   [27.27872, -26.62652],
   [27.27891, -26.62647],
   [27.27898, -26.62641],
   [27.27901, -26.62634],
   [27.279, -26.62622],
   [27.27888, -26.62603],
   [27.27872, -26.62585],
   [27.27862, -26.62571],
   [27.27853, -26.62554],
   [27.27848, -26.62544],
   [27.27848, -26.6253],
   [27.27854, -26.62522],
   [27.27859, -26.62519],
   [27.27879, -26.6252],
   [27.27897, -26.62521],
   [27.27908, -26.62521],
   [27.27918, -26.62516],
   [27.27923, -26.62507],
   [27.27925, -26.625],
   [27.27922, -26.62487],
   [27.27917, -26.62472],
   [27.27914, -26.62465],
   [27.27916, -26.62457],
   [27.27922, -26.62452],
   [27.27934, -26.62445],
   [27.27946, -26.62445],
   [27.27958, -26.62449],
   [27.27966, -26.62452],
   [27.27976, -26.62465],
   [27.2798, -26.6248],
   [27.2798, -26.62498],
   [27.27969, -26.62525],
   [27.27957, -26.6254],
   [27.27953, -26.62553],
   [27.27953, -26.62562],
   [27.27954, -26.62571],
   [27.27966, -26.62581],
   [27.27983, -26.62582],
   [27.28008, -26.6258],
   [27.28023, -26.62573],
   [27.2807, -26.6255],
   [27.28092, -26.62538],
   [27.28107, -26.62529],
   [27.28123, -26.62519],
   [27.28138, -26.6251],
   [27.28154, -26.62504],
   [27.28171, -26.62502],
   [27.28196, -26.62499],
   [27.28218, -26.62499],
   [27.2825, -26.62505],
   [27.28281, -26.62508],
   [27.28315, -26.6251],
   [27.28357, -26.6251],
   [27.28479, -26.62509],
   [27.28515, -26.62505],
   [27.28528, -26.62503],
   [27.28549, -26.62496],
   [27.28565, -26.62486],
   [27.2858, -26.62475],
   [27.28586, -26.62469],
   [27.28589, -26.62464],
   [27.28589, -26.62445],
   [27.28583, -26.62437],
   [27.28573, -26.62428],
   [27.2856, -26.62424],
   [27.28549, -26.62417],
   [27.28536, -26.62403],
   [27.28521, -26.6238],
   [27.28515, -26.62372],
   [27.28511, -26.62352],
   [27.28507, -26.62335],
   [27.28502, -26.62319],
   [27.28496, -26.6231],
   [27.28474, -26.62289],
   [27.28449, -26.62264],
   [27.28431, -26.62248],
   [27.2842, -26.62242],
   [27.28417, -26.62235],
   [27.28418, -26.62228],
   [27.28418, -26.62219],
   [27.28421, -26.62215],
   [27.28426, -26.62211],
   [27.28435, -26.62209],
   [27.28447, -26.62212],
   [27.28463, -26.62223],
   [27.28478, -26.62233],
   [27.2849, -26.62236],
   [27.28503, -26.62237],
   [27.28512, -26.62237],
   [27.2852, -26.62231],
   [27.28521, -26.62219],
   [27.28521, -26.62202],
   [27.28523, -26.62196],
   [27.2853, -26.62188],
   [27.28545, -26.62185],
   [27.28568, -26.62186],
   [27.28575, -26.62184],
   [27.2859, -26.62168],
   [27.28609, -26.6215],
   [27.28619, -26.62141],
   [27.28644, -26.62137],
   [27.2867, -26.62141],
   [27.28682, -26.62141],
   [27.28704, -26.62146],
   [27.2873, -26.62154],
   [27.28756, -26.62167],
   [27.28773, -26.62171],
   [27.28787, -26.62173],
   [27.2883, -26.62178],
   [27.28864, -26.62186],
   [27.28885, -26.62195],
   [27.28909, -26.62199],
   [27.28935, -26.62202],
   [27.28959, -26.62207],
   [27.2901, -26.62213],
   [27.29055, -26.62216],
   [27.29088, -26.62219],
   [27.29114, -26.62221],
   [27.2913, -26.62221],
   [27.29157, -26.62222],
   [27.29176, -26.62223],
   [27.29193, -26.62219],
   [27.29208, -26.62216],
   [27.2922, -26.62214],
   [27.29241, -26.62213],
   [27.29254, -26.62214],
   [27.29273, -26.62218],
   [27.29291, -26.62225],
   [27.29315, -26.6223],
   [27.2933, -26.6223],
   [27.29349, -26.62224],
   [27.29369, -26.62216],
   [27.29394, -26.622],
   [27.29416, -26.62188],
   [27.29434, -26.62175],
   [27.29454, -26.62159],
   [27.29465, -26.62151],
   [27.2949, -26.62139],
   [27.29512, -26.62132],
   [27.29531, -26.62126],
   [27.29547, -26.6212],
   [27.29565, -26.62109],
   [27.29584, -26.62093],
   [27.2962, -26.62063],
   [27.29641, -26.62046],
   [27.29655, -26.62036],
   [27.2967, -26.62031],
   [27.29681, -26.62028],
   [27.29688, -26.62028],
   [27.29691, -26.62035],
   [27.2969, -26.62071],
   [27.29691, -26.62096],
   [27.29702, -26.62118],
   [27.29711, -26.62132],
   [27.29721, -26.62147],
   [27.29737, -26.62164],
   [27.2976, -26.62181],
   [27.29795, -26.62196],
   [27.29845, -26.622],
   [27.29882, -26.62202],
   [27.29906, -26.62198],
   [27.299111, -26.622118],
   [27.30339, -26.62145],
   [27.30394, -26.62133],
   [27.30885, -26.62025],
   [27.31001, -26.62003],
   [27.31257, -26.6195],
   [27.32541, -26.61689],
   [27.34422, -26.61313],
   [27.33467, -26.59596],
   [27.3315, -26.59032],
   [27.33381, -26.58718],
   [27.33446, -26.58595],
   [27.33745, -26.58068],
   [27.33885, -26.57812],
   [27.33869, -26.5767],
   [27.33864, -26.57173],
   [27.3410467, -26.5719319],
   [27.34734, -26.57246],
   [27.35303, -26.57284],
   [27.35648, -26.57316],
   [27.36583, -26.57383],
   [27.36867, -26.57868],
   [27.37016, -26.58081],
   [27.37262, -26.58465],
   [27.37398, -26.58679],
   [27.37484, -26.58788],
   [27.37969, -26.59554],
   [27.38185, -26.59885],
   [27.38511, -26.60398],
   [27.38539, -26.60427],
   [27.37835, -26.61068],
   [27.38333, -26.61482],
   [27.39622, -26.62567],
   [27.40426, -26.63235],
   [27.40928, -26.63634],
   [27.42299, -26.64782],
   [27.425759, -26.649468],
   [27.43282, -26.63585],
   [27.43467, -26.63181],
   [27.4358, -26.63178],
   [27.43705, -26.63168],
   [27.44088, -26.63131],
   [27.44132, -26.6313],
   [27.44192, -26.6313],
   [27.44247, -26.63128],
   [27.44927, -26.63069],
   [27.45014, -26.63068],
   [27.452, -26.63054],
   [27.45483, -26.63033],
   [27.45909, -26.6315],
   [27.46086, -26.63204],
   [27.4637, -26.63293],
   [27.46409, -26.63306],
   [27.46954, -26.63474],
   [27.47711, -26.63711],
   [27.47989, -26.63797],
   [27.48405, -26.63927],
   [27.48987, -26.64113],
   [27.49431, -26.64251],
   [27.49589, -26.64293],
   [27.50653, -26.64623],
   [27.51679, -26.64638],
   [27.51954, -26.64641],
   [27.52599, -26.64651],
   [27.52898, -26.64655],
   [27.53098, -26.64658],
   [27.53195, -26.64659],
   [27.53291, -26.6466],
   [27.53388, -26.64662],
   [27.53484, -26.64663],
   [27.53581, -26.64664],
   [27.53677, -26.64666],
   [27.53774, -26.64667],
   [27.5387, -26.64668],
   [27.53967, -26.6467],
   [27.54063, -26.64671],
   [27.541, -26.64671],
   [27.54112, -26.64672],
   [27.54174, -26.64672],
   [27.54187, -26.64673],
   [27.54319, -26.64675],
   [27.54385, -26.64675],
   [27.54517, -26.64677],
   [27.54584, -26.64678],
   [27.54848, -26.64682],
   [27.54879, -26.64683],
   [27.5491, -26.64683],
   [27.54972, -26.64685],
   [27.55003, -26.64685],
   [27.55065, -26.64687],
   [27.55096, -26.64687],
   [27.55127, -26.64688],
   [27.55157, -26.64689],
   [27.55193, -26.64689],
   [27.552, -26.6469],
   [27.55241, -26.6469],
   [27.55254, -26.64691],
   [27.55307, -26.64691],
   [27.5532, -26.64692],
   [27.5536, -26.64692],
   [27.5539, -26.64693],
   [27.55419, -26.64693],
   [27.55449, -26.64694],
   [27.55479, -26.64694],
   [27.55508, -26.64695],
   [27.55568, -26.64695],
   [27.55597, -26.64696],
   [27.55627, -26.64696],
   [27.55657, -26.64697],
   [27.55907, -26.64701],
   [27.56033, -26.64702],
   [27.56408, -26.64708],
   [27.56534, -26.6471],
   [27.56909, -26.64716],
   [27.56914, -26.64926],
   [27.56918, -26.65135],
   [27.5693, -26.65765],
   [27.56934, -26.65974],
   [27.56938, -26.66184],
   [27.56943, -26.66394],
   [27.56947, -26.66604],
   [27.56951, -26.66813],
   [27.56952, -26.66871],
   [27.56957, -26.67197],
   [27.56986, -26.67698],
   [27.57024, -26.68365],
   [27.57423, -26.68408],
   [27.57422, -26.68749],
   [27.57418, -26.69525],
   [27.57415, -26.70935],
   [27.57414, -26.71129],
   [27.57412, -26.71503],
   [27.57416, -26.71584],
   [27.57531, -26.71569],
   [27.59246, -26.70121],
   [27.60284, -26.69244],
   [27.60259, -26.69473],
   [27.60217, -26.70375],
   [27.60166, -26.71486],
   [27.60224, -26.72285],
   [27.58912, -26.72409],
   [27.58691, -26.72729],
   [27.58448, -26.72851],
   [27.58374, -26.72911],
   [27.58141, -26.731],
   [27.58314, -26.7321],
   [27.58399, -26.73263],
   [27.58881, -26.7357],
   [27.59043, -26.73836],
   [27.59221, -26.73757],
   [27.59239, -26.73751],
   [27.59269, -26.73743],
   [27.59312, -26.73736],
   [27.59358, -26.73714],
   [27.59418, -26.73704],
   [27.59476, -26.73708],
   [27.59512, -26.73712],
   [27.59554, -26.73715],
   [27.5961, -26.73723],
   [27.59668, -26.7373],
   [27.5969, -26.73742],
   [27.59732, -26.73773],
   [27.59771, -26.73811],
   [27.59792, -26.73838],
   [27.59833, -26.73887],
   [27.59878, -26.7393],
   [27.59929, -26.73969],
   [27.59968, -26.73999],
   [27.6003, -26.74032],
   [27.60088, -26.74059],
   [27.60133, -26.74077],
   [27.60193, -26.74094],
   [27.60217, -26.74102],
   [27.60263, -26.74102],
   [27.60288, -26.74095],
   [27.60324, -26.74083],
   [27.60376, -26.74065],
   [27.60409, -26.74063],
   [27.60449, -26.74068],
   [27.6048, -26.74077],
   [27.60513, -26.74096],
   [27.60571, -26.74122],
   [27.6061, -26.74132],
   [27.60635, -26.74133],
   [27.60672, -26.74127],
   [27.60719, -26.74109],
   [27.60743, -26.74089],
   [27.60785, -26.74046],
   [27.60835, -26.7397],
   [27.60857, -26.73938],
   [27.60871, -26.73916],
   [27.60897, -26.73857],
   [27.60905, -26.73819],
   [27.60908, -26.73775],
   [27.60918, -26.73707],
   [27.60926, -26.73643],
   [27.60928, -26.73596],
   [27.60921, -26.73554],
   [27.6091, -26.73514],
   [27.6091, -26.73473],
   [27.60924, -26.73411],
   [27.60946, -26.73344],
   [27.60986, -26.73293],
   [27.61025, -26.73269],
   [27.61049, -26.7326],
   [27.61102, -26.73257],
   [27.61151, -26.73259],
   [27.61202, -26.73255],
   [27.61258, -26.73251],
   [27.61312, -26.73247],
   [27.61347, -26.73244],
   [27.61391, -26.73245],
   [27.61449, -26.73255],
   [27.61492, -26.73267],
   [27.6154, -26.73272],
   [27.61622, -26.73279],
   [27.616834, -26.732746],
   [27.61692, -26.73274],
   [27.6175, -26.7326],
   [27.61799, -26.7326],
   [27.61885, -26.73259],
   [27.61996, -26.73251],
   [27.62042, -26.73241],
   [27.6209, -26.73237],
   [27.62136, -26.73241],
   [27.6219, -26.73255],
   [27.62248, -26.73261],
   [27.62322, -26.73266],
   [27.62427, -26.73265],
   [27.62459, -26.73266],
   [27.62539, -26.73255],
   [27.62599, -26.73251],
   [27.62631, -26.73245],
   [27.62678, -26.73244],
   [27.62825, -26.73238],
   [27.62952, -26.73235],
   [27.62986, -26.73243],
   [27.63049, -26.73254],
   [27.63086, -26.73256],
   [27.63147, -26.73266],
   [27.63187, -26.73274],
   [27.63247, -26.73299],
   [27.63294, -26.73337],
   [27.63341, -26.7337],
   [27.6338, -26.73437],
   [27.63406, -26.73479],
   [27.63429, -26.73527],
   [27.63447, -26.73574],
   [27.63454, -26.73629],
   [27.63459, -26.73711],
   [27.63465, -26.73833],
   [27.63465, -26.7388],
   [27.63461, -26.73903],
   [27.63441, -26.73964],
   [27.63412, -26.74043],
   [27.63362, -26.74151],
   [27.63329, -26.74208],
   [27.63308, -26.74241],
   [27.6329, -26.74279],
   [27.63264, -26.74341],
   [27.6324, -26.74397],
   [27.63235, -26.74435],
   [27.63231, -26.74489],
   [27.63229, -26.74514],
   [27.6323, -26.74549],
   [27.6324, -26.74596],
   [27.63272, -26.74664],
   [27.63344, -26.74783],
   [27.6337, -26.74812],
   [27.63383, -26.74827],
   [27.63409, -26.74873],
   [27.63431, -26.74909],
   [27.63513, -26.75023],
   [27.63542, -26.75062],
   [27.63561, -26.75092],
   [27.63579, -26.75131],
   [27.63578, -26.75151],
   [27.6357, -26.75194],
   [27.63553, -26.75251],
   [27.63525, -26.75306],
   [27.63501, -26.75356],
   [27.63479, -26.75377],
   [27.63464, -26.75393],
   [27.63432, -26.75432],
   [27.63402, -26.75464],
   [27.63371, -26.75507],
   [27.63354, -26.75533],
   [27.63342, -26.75552],
   [27.63332, -26.75569],
   [27.63325, -26.75602],
   [27.63319, -26.75619],
   [27.63311, -26.75656],
   [27.63303, -26.75673],
   [27.63292, -26.75692],
   [27.63267, -26.75765],
   [27.63243, -26.75808],
   [27.63231, -26.75827],
   [27.63211, -26.75865],
   [27.63186, -26.75914],
   [27.63153, -26.75952],
   [27.63128, -26.7599],

In [49]:
gauteng = pd.DataFrame({"name":["Gauteng"],"color":['red']})

# gdf = gpd.GeoDataFrame.from_features(
#     gauteng_geojson["features"]
# ).merge(gauteng, on="name").set_index("name")

fig = px.choropleth(gauteng, geojson=gauteng_geojson, color="color",
                    locations="name", featureidkey="properties.name",
                    projection="mercator",
                   )
fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show(renderer="browser")

In [4]:
# Load GeoJSON
import json


with open("../data/processed/gauteng_adm2.geojson") as f:
    gjson = json.load(f)

yield_df = pd.read_csv("../data/processed/yield.csv")

In [7]:
for feature in gjson["features"]:
    print(feature["properties"]["adm2_name"])

City of Johannesburg
City of Tshwane
Ekurhuleni
Sedibeng
West Rand

In [11]:
# Load GeoJSON
gdf = gpd.read_file("../data/processed/gauteng_adm2.geojson")

# Merge metrics
gdf_plot = gdf.merge(yield_df, on="adm2_name", how="left")

# Convert to WGS84
gdf_plot = gdf_plot.to_crs(epsg=4326)

print(set(gdf_plot["adm2_name"]) - set(yield_df["adm2_name"]))

set()

In [ ]:
with open("../data/gadm41_ZAF_3.json") as f:
    test = json.load(f)

In [70]:
test['features'][3]

{'type': 'Feature',
 'properties': {'GID_4': 'ZAF.1.1.1.4_1',
  'GID_0': 'ZAF',
  'COUNTRY': 'SouthAfrica',
  'GID_1': 'ZAF.1_1',
  'NAME_1': 'EasternCape',
  'GID_2': 'ZAF.1.1_1',
  'NAME_2': 'AlfredNzo',
  'GID_3': 'ZAF.1.1.1_1',
  'NAME_3': 'Matatiele',
  'NAME_4': '12',
  'VARNAME_4': 'NA',
  'TYPE_4': 'Ward',
  'ENGTYPE_4': 'Ward',
  'CC_4': '24401012'},
 'geometry': {'type': 'MultiPolygon',
  'coordinates': [[[[28.4507, -30.1939],
     [28.4598, -30.1872],
     [28.4625, -30.1903],
     [28.4676, -30.1886],
     [28.4794, -30.1893],
     [28.4963, -30.1983],
     [28.5071, -30.1955],
     [28.5247, -30.2069],
     [28.535, -30.2044],
     [28.5369, -30.2064],
     [28.5367, -30.2091],
     [28.5398, -30.212],
     [28.5461, -30.2132],
     [28.5455, -30.2181],
     [28.5427, -30.2173],
     [28.5406, -30.2201],
     [28.545, -30.2213],
     [28.5499, -30.2256],
     [28.554, -30.2272],
     [28.557, -30.2254],
     [28.5584, -30.2203],
     [28.5653, -30.2208],
     [28.5672, -30.2281],
     [28.5547, -30.2341],
     [28.5533, -30.2387],
     [28.5499, -30.2387],
     [28.5482, -30.2433],
     [28.5508, -30.249],
     [28.5489, -30.2629],
     [28.5503, -30.2649],
     [28.5487, -30.2682],
     [28.5511, -30.2701],
     [28.5489, -30.2727],
     [28.5519, -30.2751],
     [28.5502, -30.2761],
     [28.5517, -30.2775],
     [28.5498, -30.2806],
     [28.5453, -30.2837],
     [28.5454, -30.2815],
     [28.5443, -30.2834],
     [28.5403, -30.2839],
     [28.5402, -30.2825],
     [28.5387, -30.2835],
     [28.5394, -30.2844],
     [28.5358, -30.2855],
     [28.533, -30.2835],
     [28.5301, -30.2854],
     [28.5287, -30.283],
     [28.5265, -30.2852],
     [28.5259, -30.2832],
     [28.5259, -30.2845],
     [28.5216, -30.2858],
     [28.5225, -30.2864],
     [28.5194, -30.2863],
     [28.5212, -30.2875],
     [28.5201, -30.2897],
     [28.5177, -30.2864],
     [28.5179, -30.2822],
     [28.5232, -30.2637],
     [28.5165, -30.261],
     [28.5192, -30.2585],
     [28.5183, -30.2574],
     [28.5232, -30.2554],
     [28.5232, -30.2593],
     [28.5248, -30.26],
     [28.5271, -30.2529],
     [28.5256, -30.2507],
     [28.5016, -30.2509],
     [28.4975, -30.248],
     [28.4965, -30.2497],
     [28.4942, -30.2485],
     [28.4889, -30.2509],
     [28.4876, -30.2494],
     [28.4859, -30.2512],
     [28.4836, -30.2506],
     [28.4846, -30.248],
     [28.481, -30.249],
     [28.4807, -30.2519],
     [28.4783, -30.252],
     [28.4797, -30.2544],
     [28.478, -30.255],
     [28.4753, -30.2508],
     [28.4749, -30.245],
     [28.4728, -30.244],
     [28.4663, -30.2463],
     [28.4633, -30.2454],
     [28.4604, -30.2498],
     [28.4569, -30.2496],
     [28.4554, -30.2464],
     [28.4515, -30.2468],
     [28.4491, -30.2493],
     [28.4463, -30.245],
     [28.4436, -30.2442],
     [28.4427, -30.2383],
     [28.4471, -30.2352],
     [28.448, -30.2244],
     [28.4467, -30.2201],
     [28.4495, -30.2153],
     [28.4503, -30.2099],
     [28.4501, -30.2043],
     [28.4477, -30.2003],
     [28.4507, -30.1939]]]]}}

In [71]:
for feat in test['features']:
    print(feat['properties']['NAME_4'], feat['properties']['NAME_3'], feat['properties']['NAME_2'], feat['properties']['NAME_1'])

1 Matatiele AlfredNzo EasternCape
10 Matatiele AlfredNzo EasternCape
11 Matatiele AlfredNzo EasternCape
12 Matatiele AlfredNzo EasternCape
13 Matatiele AlfredNzo EasternCape
14 Matatiele AlfredNzo EasternCape
15 Matatiele AlfredNzo EasternCape
16 Matatiele AlfredNzo EasternCape
17 Matatiele AlfredNzo EasternCape
18 Matatiele AlfredNzo EasternCape
19 Matatiele AlfredNzo EasternCape
2 Matatiele AlfredNzo EasternCape
20 Matatiele AlfredNzo EasternCape
21 Matatiele AlfredNzo EasternCape
22 Matatiele AlfredNzo EasternCape
23 Matatiele AlfredNzo EasternCape
24 Matatiele AlfredNzo EasternCape
25 Matatiele AlfredNzo EasternCape
26 Matatiele AlfredNzo EasternCape
3 Matatiele AlfredNzo EasternCape
4 Matatiele AlfredNzo EasternCape
5 Matatiele AlfredNzo EasternCape
6 Matatiele AlfredNzo EasternCape
7 Matatiele AlfredNzo EasternCape
8 Matatiele AlfredNzo EasternCape
9 Matatiele AlfredNzo EasternCape
1 Mbizana AlfredNzo EasternCape
10 Mbizana AlfredNzo EasternCape
11 Mbizana AlfredNzo EasternCape
12 Mbizana AlfredNzo EasternCape
13 Mbizana AlfredNzo EasternCape
14 Mbizana AlfredNzo EasternCape
15 Mbizana AlfredNzo EasternCape
16 Mbizana AlfredNzo EasternCape
17 Mbizana AlfredNzo EasternCape
18 Mbizana AlfredNzo EasternCape
19 Mbizana AlfredNzo EasternCape
2 Mbizana AlfredNzo EasternCape
20 Mbizana AlfredNzo EasternCape
21 Mbizana AlfredNzo EasternCape
22 Mbizana AlfredNzo EasternCape
23 Mbizana AlfredNzo EasternCape
24 Mbizana AlfredNzo EasternCape
25 Mbizana AlfredNzo EasternCape
26 Mbizana AlfredNzo EasternCape
27 Mbizana AlfredNzo EasternCape
28 Mbizana AlfredNzo EasternCape
29 Mbizana AlfredNzo EasternCape
3 Mbizana AlfredNzo EasternCape
30 Mbizana AlfredNzo EasternCape
31 Mbizana AlfredNzo EasternCape
4 Mbizana AlfredNzo EasternCape
5 Mbizana AlfredNzo EasternCape
6 Mbizana AlfredNzo EasternCape
7 Mbizana AlfredNzo EasternCape
8 Mbizana AlfredNzo EasternCape
9 Mbizana AlfredNzo EasternCape
1 Ntabankulu AlfredNzo EasternCape
10 Ntabankulu AlfredNzo EasternCape
11 Ntabankulu AlfredNzo EasternCape
12 Ntabankulu AlfredNzo EasternCape
13 Ntabankulu AlfredNzo EasternCape
14 Ntabankulu AlfredNzo EasternCape
15 Ntabankulu AlfredNzo EasternCape
16 Ntabankulu AlfredNzo EasternCape
17 Ntabankulu AlfredNzo EasternCape
18 Ntabankulu AlfredNzo EasternCape
2 Ntabankulu AlfredNzo EasternCape
3 Ntabankulu AlfredNzo EasternCape
4 Ntabankulu AlfredNzo EasternCape
5 Ntabankulu AlfredNzo EasternCape
6 Ntabankulu AlfredNzo EasternCape
7 Ntabankulu AlfredNzo EasternCape
8 Ntabankulu AlfredNzo EasternCape
9 Ntabankulu AlfredNzo EasternCape
1 Umzimvubu AlfredNzo EasternCape
10 Umzimvubu AlfredNzo EasternCape
11 Umzimvubu AlfredNzo EasternCape
12 Umzimvubu AlfredNzo EasternCape
13 Umzimvubu AlfredNzo EasternCape
14 Umzimvubu AlfredNzo EasternCape
15 Umzimvubu AlfredNzo EasternCape
16 Umzimvubu AlfredNzo EasternCape
17 Umzimvubu AlfredNzo EasternCape
18 Umzimvubu AlfredNzo EasternCape
19 Umzimvubu AlfredNzo EasternCape
2 Umzimvubu AlfredNzo EasternCape
20 Umzimvubu AlfredNzo EasternCape
21 Umzimvubu AlfredNzo EasternCape
22 Umzimvubu AlfredNzo EasternCape
23 Umzimvubu AlfredNzo EasternCape
24 Umzimvubu AlfredNzo EasternCape
25 Umzimvubu AlfredNzo EasternCape
26 Umzimvubu AlfredNzo EasternCape
27 Umzimvubu AlfredNzo EasternCape
3 Umzimvubu AlfredNzo EasternCape
4 Umzimvubu AlfredNzo EasternCape
5 Umzimvubu AlfredNzo EasternCape
6 Umzimvubu AlfredNzo EasternCape
7 Umzimvubu AlfredNzo EasternCape
8 Umzimvubu AlfredNzo EasternCape
9 Umzimvubu AlfredNzo EasternCape
1 Amahlathi Amathole EasternCape
10 Amahlathi Amathole EasternCape
11 Amahlathi Amathole EasternCape
12 Amahlathi Amathole EasternCape
13 Amahlathi Amathole EasternCape
14 Amahlathi Amathole EasternCape
15 Amahlathi Amathole EasternCape
16 Amahlathi Amathole EasternCape
17 Amahlathi Amathole EasternCape
18 Amahlathi Amathole EasternCape
19 Amahlathi Amathole EasternCape
2 Amahlathi Amathole EasternCape
20 Amahlathi Amathole EasternCape
3 Amahlathi Amathole EasternCape
4 Amahlathi Amathole EasternCape
5 Amahlathi Amathole EasternCape
6 Amahlathi Amathole EasternCape
7 Amahlathi Amathole EasternCape
8 Amahlathi Amathole EasternCape
9 Amahlathi Amathole EasternCape
1 GreatKei Amathole EasternCape
2 GreatKei Amathole EasternCape
3 GreatKei Amathole EasternCape
4 GreatKei Amathole EasternCape
5 GreatKei Amathole EasternCape
6 GreatKei Amathole EasternCape
7 GreatKei Amathole EasternCape
1 Mbhashe Amathole EasternCape
10 Mbhashe Amathole EasternCape
11 Mbhashe Amathole EasternCape
12 Mbhashe Amathole EasternCape
13 Mbhashe Amathole EasternCape
14 Mbhashe Amathole EasternCape
15 Mbhashe Amathole EasternCape
16 Mbhashe Amathole EasternCape
17 Mbhashe Amathole EasternCape
18 Mbhashe Amathole EasternCape
19 Mbhashe Amathole EasternCape
2 Mbhashe Amathole EasternCape
20 Mbhashe Amathole EasternCape
21 Mbhashe Amathole EasternCape
22 Mbhashe Amathole EasternCape
23 Mbhashe Amathole EasternCape
24 Mbhashe Amathole EasternCape
25 Mbhashe Amathole EasternCape
26 Mbhashe Amathole EasternCape
27 Mbhashe Amathole EasternCape
28 Mbhashe Amathole EasternCape
29 Mbhashe Amathole EasternCape
3 Mbhashe Amathole EasternCape
30 Mbhashe Amathole EasternCape
31 Mbhashe Amathole EasternCape
4 Mbhashe Amathole EasternCape
5 Mbhashe Amathole EasternCape
6 Mbhashe Amathole EasternCape
7 Mbhashe Amathole EasternCape
8 Mbhashe Amathole EasternCape
9 Mbhashe Amathole EasternCape
1 Mnquma Amathole EasternCape
10 Mnquma Amathole EasternCape
11 Mnquma Amathole EasternCape
12 Mnquma Amathole EasternCape
13 Mnquma Amathole EasternCape
14 Mnquma Amathole EasternCape
15 Mnquma Amathole EasternCape
16 Mnquma Amathole EasternCape
17 Mnquma Amathole EasternCape
18 Mnquma Amathole EasternCape
19 Mnquma Amathole EasternCape
2 Mnquma Amathole EasternCape
20 Mnquma Amathole EasternCape
21 Mnquma Amathole EasternCape
22 Mnquma Amathole EasternCape
23 Mnquma Amathole EasternCape
24 Mnquma Amathole EasternCape
25 Mnquma Amathole EasternCape
26 Mnquma Amathole EasternCape
27 Mnquma Amathole EasternCape
28 Mnquma Amathole EasternCape
29 Mnquma Amathole EasternCape
3 Mnquma Amathole EasternCape
30 Mnquma Amathole EasternCape
31 Mnquma Amathole EasternCape
4 Mnquma Amathole EasternCape
5 Mnquma Amathole EasternCape
6 Mnquma Amathole EasternCape
7 Mnquma Amathole EasternCape
8 Mnquma Amathole EasternCape
9 Mnquma Amathole EasternCape
1 Ngqushwa Amathole EasternCape
10 Ngqushwa Amathole EasternCape
11 Ngqushwa Amathole EasternCape
12 Ngqushwa Amathole EasternCape
13 Ngqushwa Amathole EasternCape
2 Ngqushwa Amathole EasternCape
3 Ngqushwa Amathole EasternCape
4 Ngqushwa Amathole EasternCape
5 Ngqushwa Amathole EasternCape
6 Ngqushwa Amathole EasternCape
7 Ngqushwa Amathole EasternCape
8 Ngqushwa Amathole EasternCape
9 Ngqushwa Amathole EasternCape
1 Nkonkobe Amathole EasternCape
10 Nkonkobe Amathole EasternCape
11 Nkonkobe Amathole EasternCape
12 Nkonkobe Amathole EasternCape
13 Nkonkobe Amathole EasternCape
14 Nkonkobe Amathole EasternCape
15 Nkonkobe Amathole EasternCape
16 Nkonkobe Amathole EasternCape
17 Nkonkobe Amathole EasternCape
18 Nkonkobe Amathole EasternCape
19 Nkonkobe Amathole EasternCape
2 Nkonkobe Amathole EasternCape
20 Nkonkobe Amathole EasternCape
21 Nkonkobe Amathole EasternCape
3 Nkonkobe Amathole EasternCape
4 Nkonkobe Amathole EasternCape
5 Nkonkobe Amathole EasternCape
6 Nkonkobe Amathole EasternCape
7 Nkonkobe Amathole EasternCape
8 Nkonkobe Amathole EasternCape
9 Nkonkobe Amathole EasternCape
1 Nxuba Amathole EasternCape
2 Nxuba Amathole EasternCape
3 Nxuba Amathole EasternCape
4 Nxuba Amathole EasternCape
1 BuffaloCity BuffaloCity EasternCape
10 BuffaloCity BuffaloCity EasternCape
11 BuffaloCity BuffaloCity EasternCape
12 BuffaloCity BuffaloCity EasternCape
13 BuffaloCity BuffaloCity EasternCape
14 BuffaloCity BuffaloCity EasternCape
15 BuffaloCity BuffaloCity EasternCape
16 BuffaloCity BuffaloCity EasternCape
17 BuffaloCity BuffaloCity EasternCape
18 BuffaloCity BuffaloCity EasternCape
19 BuffaloCity BuffaloCity EasternCape
2 BuffaloCity BuffaloCity EasternCape
20 BuffaloCity BuffaloCity EasternCape
21 BuffaloCity BuffaloCity EasternCape
22 BuffaloCity BuffaloCity EasternCape
23 BuffaloCity BuffaloCity EasternCape
24 BuffaloCity BuffaloCity EasternCape
25 BuffaloCity BuffaloCity EasternCape
26 BuffaloCity BuffaloCity EasternCape
27 BuffaloCity BuffaloCity EasternCape
28 BuffaloCity BuffaloCity EasternCape
29 BuffaloCity BuffaloCity EasternCape
3 BuffaloCity BuffaloCity EasternCape
30 BuffaloCity BuffaloCity EasternCape
31 BuffaloCity BuffaloCity EasternCape
32 BuffaloCity BuffaloCity EasternCape
33 BuffaloCity BuffaloCity EasternCape
34 BuffaloCity BuffaloCity EasternCape
35 BuffaloCity BuffaloCity EasternCape
36 BuffaloCity BuffaloCity EasternCape
37 BuffaloCity BuffaloCity EasternCape
38 BuffaloCity BuffaloCity EasternCape
39 BuffaloCity BuffaloCity EasternCape
4 BuffaloCity BuffaloCity EasternCape
40 BuffaloCity BuffaloCity EasternCape
41 BuffaloCity BuffaloCity EasternCape
42 BuffaloCity BuffaloCity EasternCape
43 BuffaloCity BuffaloCity EasternCape
44 BuffaloCity BuffaloCity EasternCape
45 BuffaloCity BuffaloCity EasternCape
46 BuffaloCity BuffaloCity EasternCape
47 BuffaloCity BuffaloCity EasternCape
48 BuffaloCity BuffaloCity EasternCape
49 BuffaloCity BuffaloCity EasternCape
5 BuffaloCity BuffaloCity EasternCape
50 BuffaloCity BuffaloCity EasternCape
6 BuffaloCity BuffaloCity EasternCape
7 BuffaloCity BuffaloCity EasternCape
8 BuffaloCity BuffaloCity EasternCape
9 BuffaloCity BuffaloCity EasternCape
1 Baviaans Cacadu EasternCape
2 Baviaans Cacadu EasternCape
3 Baviaans Cacadu EasternCape
4 Baviaans Cacadu EasternCape
1 BlueCraneRoute Cacadu EasternCape
2 BlueCraneRoute Cacadu EasternCape
3 BlueCraneRoute Cacadu EasternCape
4 BlueCraneRoute Cacadu EasternCape
5 BlueCraneRoute Cacadu EasternCape
6 BlueCraneRoute Cacadu EasternCape
1 Camdeboo Cacadu EasternCape
2 Camdeboo Cacadu EasternCape
3 Camdeboo Cacadu EasternCape
4 Camdeboo Cacadu EasternCape
5 Camdeboo Cacadu EasternCape
6 Camdeboo Cacadu EasternCape
7 Camdeboo Cacadu EasternCape
1 Ikwezi Cacadu EasternCape
2 Ikwezi Cacadu EasternCape
3 Ikwezi Cacadu EasternCape
4 Ikwezi Cacadu EasternCape
1 Kou-Kamma Cacadu EasternCape
2 Kou-Kamma Cacadu EasternCape
3 Kou-Kamma Cacadu EasternCape
4 Kou-Kamma Cacadu EasternCape
5 Kou-Kamma Cacadu EasternCape
6 Kou-Kamma Cacadu EasternCape
1 Kouga Cacadu EasternCape
10 Kouga Cacadu EasternCape
11 Kouga Cacadu EasternCape
12 Kouga Cacadu EasternCape
13 Kouga Cacadu EasternCape
14 Kouga Cacadu EasternCape
15 Kouga Cacadu EasternCape
2 Kouga Cacadu EasternCape
3 Kouga Cacadu EasternCape
4 Kouga Cacadu EasternCape
5 Kouga Cacadu EasternCape
6 Kouga Cacadu EasternCape
7 Kouga Cacadu EasternCape
8 Kouga Cacadu EasternCape
9 Kouga Cacadu EasternCape
1 Makana Cacadu EasternCape
10 Makana Cacadu EasternCape
11 Makana Cacadu EasternCape
12 Makana Cacadu EasternCape
13 Makana Cacadu EasternCape
14 Makana Cacadu EasternCape
2 Makana Cacadu EasternCape
3 Makana Cacadu EasternCape
4 Makana Cacadu EasternCape
5 Makana Cacadu EasternCape
6 Makana Cacadu EasternCape
7 Makana Cacadu EasternCape
8 Makana Cacadu EasternCape
9 Makana Cacadu EasternCape
1 Ndlambe Cacadu EasternCape
10 Ndlambe Cacadu EasternCape
2 Ndlambe Cacadu EasternCape
3 Ndlambe Cacadu EasternCape
4 Ndlambe Cacadu EasternCape
5 Ndlambe Cacadu EasternCape
6 Ndlambe Cacadu EasternCape
7 Ndlambe Cacadu EasternCape
8 Ndlambe Cacadu EasternCape
9 Ndlambe Cacadu EasternCape
1 SundaysRiverValley Cacadu EasternCape
2 SundaysRiverValley Cacadu EasternCape
3 SundaysRiverValley Cacadu EasternCape
4 SundaysRiverValley Cacadu EasternCape
5 SundaysRiverValley Cacadu EasternCape
6 SundaysRiverValley Cacadu EasternCape
7 SundaysRiverValley Cacadu EasternCape
8 SundaysRiverValley Cacadu EasternCape
1 Emalahleni ChrisHani EasternCape
10 Emalahleni ChrisHani EasternCape
11 Emalahleni ChrisHani EasternCape
12 Emalahleni ChrisHani EasternCape
13 Emalahleni ChrisHani EasternCape
14 Emalahleni ChrisHani EasternCape
15 Emalahleni ChrisHani EasternCape
16 Emalahleni ChrisHani EasternCape
17 Emalahleni ChrisHani EasternCape
2 Emalahleni ChrisHani EasternCape
3 Emalahleni ChrisHani EasternCape
4 Emalahleni ChrisHani EasternCape
5 Emalahleni ChrisHani EasternCape
6 Emalahleni ChrisHani EasternCape
7 Emalahleni ChrisHani EasternCape
8 Emalahleni ChrisHani EasternCape
9 Emalahleni ChrisHani EasternCape
1 Engcobo ChrisHani EasternCape
10 Engcobo ChrisHani EasternCape
11 Engcobo ChrisHani EasternCape
12 Engcobo ChrisHani EasternCape
13 Engcobo ChrisHani EasternCape
14 Engcobo ChrisHani EasternCape
15 Engcobo ChrisHani EasternCape
16 Engcobo ChrisHani EasternCape
17 Engcobo ChrisHani EasternCape
18 Engcobo ChrisHani EasternCape
19 Engcobo ChrisHani EasternCape
2 Engcobo ChrisHani EasternCape
20 Engcobo ChrisHani EasternCape
3 Engcobo ChrisHani EasternCape
4 Engcobo ChrisHani EasternCape
5 Engcobo ChrisHani EasternCape
6 Engcobo ChrisHani EasternCape
7 Engcobo ChrisHani EasternCape
8 Engcobo ChrisHani EasternCape
9 Engcobo ChrisHani EasternCape
1 Inkwanca ChrisHani EasternCape
2 Inkwanca ChrisHani EasternCape
3 Inkwanca ChrisHani EasternCape
4 Inkwanca ChrisHani EasternCape
1 IntsikaYethu ChrisHani EasternCape
10 IntsikaYethu ChrisHani EasternCape
11 IntsikaYethu ChrisHani EasternCape
12 IntsikaYethu ChrisHani EasternCape
13 IntsikaYethu ChrisHani EasternCape
14 IntsikaYethu ChrisHani EasternCape
15 IntsikaYethu ChrisHani EasternCape
16 IntsikaYethu ChrisHani EasternCape
17 IntsikaYethu ChrisHani EasternCape
18 IntsikaYethu ChrisHani EasternCape
19 IntsikaYethu ChrisHani EasternCape
2 IntsikaYethu ChrisHani EasternCape
20 IntsikaYethu ChrisHani EasternCape
21 IntsikaYethu ChrisHani EasternCape
3 IntsikaYethu ChrisHani EasternCape
4 IntsikaYethu ChrisHani EasternCape
5 IntsikaYethu ChrisHani EasternCape
6 IntsikaYethu ChrisHani EasternCape
7 IntsikaYethu ChrisHani EasternCape
8 IntsikaYethu ChrisHani EasternCape
9 IntsikaYethu ChrisHani EasternCape
1 InxubaYethemba ChrisHani EasternCape
2 InxubaYethemba ChrisHani EasternCape
3 InxubaYethemba ChrisHani EasternCape
4 InxubaYethemba ChrisHani EasternCape
5 InxubaYethemba ChrisHani EasternCape
6 InxubaYethemba ChrisHani EasternCape
7 InxubaYethemba ChrisHani EasternCape
8 InxubaYethemba ChrisHani EasternCape
9 InxubaYethemba ChrisHani EasternCape
1 Lukanji ChrisHani EasternCape
10 Lukanji ChrisHani EasternCape
11 Lukanji ChrisHani EasternCape
12 Lukanji ChrisHani EasternCape
13 Lukanji ChrisHani EasternCape
14 Lukanji ChrisHani EasternCape
15 Lukanji ChrisHani EasternCape
16 Lukanji ChrisHani EasternCape
17 Lukanji ChrisHani EasternCape
18 Lukanji ChrisHani EasternCape
19 Lukanji ChrisHani EasternCape
2 Lukanji ChrisHani EasternCape
20 Lukanji ChrisHani EasternCape
21 Lukanji ChrisHani EasternCape
22 Lukanji ChrisHani EasternCape
23 Lukanji ChrisHani EasternCape
24 Lukanji ChrisHani EasternCape
25 Lukanji ChrisHani EasternCape
26 Lukanji ChrisHani EasternCape
27 Lukanji ChrisHani EasternCape
3 Lukanji ChrisHani EasternCape
4 Lukanji ChrisHani EasternCape
5 Lukanji ChrisHani EasternCape
6 Lukanji ChrisHani EasternCape
7 Lukanji ChrisHani EasternCape
8 Lukanji ChrisHani EasternCape
9 Lukanji ChrisHani EasternCape
1 Sakhisizwe ChrisHani EasternCape
2 Sakhisizwe ChrisHani EasternCape
3 Sakhisizwe ChrisHani EasternCape
4 Sakhisizwe ChrisHani EasternCape
5 Sakhisizwe ChrisHani EasternCape
6 Sakhisizwe ChrisHani EasternCape
7 Sakhisizwe ChrisHani EasternCape
8 Sakhisizwe ChrisHani EasternCape
9 Sakhisizwe ChrisHani EasternCape
1 Tsolwana ChrisHani EasternCape
2 Tsolwana ChrisHani EasternCape
3 Tsolwana ChrisHani EasternCape
4 Tsolwana ChrisHani EasternCape
5 Tsolwana ChrisHani EasternCape
1 Elundini JoeGqabi EasternCape
10 Elundini JoeGqabi EasternCape
11 Elundini JoeGqabi EasternCape
12 Elundini JoeGqabi EasternCape
13 Elundini JoeGqabi EasternCape
14 Elundini JoeGqabi EasternCape
15 Elundini JoeGqabi EasternCape
16 Elundini JoeGqabi EasternCape
17 Elundini JoeGqabi EasternCape
2 Elundini JoeGqabi EasternCape
3 Elundini JoeGqabi EasternCape
4 Elundini JoeGqabi EasternCape
5 Elundini JoeGqabi EasternCape
6 Elundini JoeGqabi EasternCape
7 Elundini JoeGqabi EasternCape
8 Elundini JoeGqabi EasternCape
9 Elundini JoeGqabi EasternCape
1 Gariep JoeGqabi EasternCape
2 Gariep JoeGqabi EasternCape
3 Gariep JoeGqabi EasternCape
4 Gariep JoeGqabi EasternCape
5 Gariep JoeGqabi EasternCape
1 Maletswai JoeGqabi EasternCape
2 Maletswai JoeGqabi EasternCape
3 Maletswai JoeGqabi EasternCape
4 Maletswai JoeGqabi EasternCape
5 Maletswai JoeGqabi EasternCape
6 Maletswai JoeGqabi EasternCape
1 Senqu JoeGqabi EasternCape
10 Senqu JoeGqabi EasternCape
11 Senqu JoeGqabi EasternCape
12 Senqu JoeGqabi EasternCape
13 Senqu JoeGqabi EasternCape
14 Senqu JoeGqabi EasternCape
15 Senqu JoeGqabi EasternCape
16 Senqu JoeGqabi EasternCape
17 Senqu JoeGqabi EasternCape
18 Senqu JoeGqabi EasternCape
19 Senqu JoeGqabi EasternCape
2 Senqu JoeGqabi EasternCape
3 Senqu JoeGqabi EasternCape
4 Senqu JoeGqabi EasternCape
5 Senqu JoeGqabi EasternCape
6 Senqu JoeGqabi EasternCape
7 Senqu JoeGqabi EasternCape
8 Senqu JoeGqabi EasternCape
9 Senqu JoeGqabi EasternCape
1 NelsonMandelaBay NelsonMandelaBay EasternCape
10 NelsonMandelaBay NelsonMandelaBay EasternCape
11 NelsonMandelaBay NelsonMandelaBay EasternCape
12 NelsonMandelaBay NelsonMandelaBay EasternCape
13 NelsonMandelaBay NelsonMandelaBay EasternCape
14 NelsonMandelaBay NelsonMandelaBay EasternCape
15 NelsonMandelaBay NelsonMandelaBay EasternCape
16 NelsonMandelaBay NelsonMandelaBay EasternCape
17 NelsonMandelaBay NelsonMandelaBay EasternCape
18 NelsonMandelaBay NelsonMandelaBay EasternCape
19 NelsonMandelaBay NelsonMandelaBay EasternCape
2 NelsonMandelaBay NelsonMandelaBay EasternCape
20 NelsonMandelaBay NelsonMandelaBay EasternCape
21 NelsonMandelaBay NelsonMandelaBay EasternCape
22 NelsonMandelaBay NelsonMandelaBay EasternCape
23 NelsonMandelaBay NelsonMandelaBay EasternCape
24 NelsonMandelaBay NelsonMandelaBay EasternCape
25 NelsonMandelaBay NelsonMandelaBay EasternCape
26 NelsonMandelaBay NelsonMandelaBay EasternCape
27 NelsonMandelaBay NelsonMandelaBay EasternCape
28 NelsonMandelaBay NelsonMandelaBay EasternCape
29 NelsonMandelaBay NelsonMandelaBay EasternCape
3 NelsonMandelaBay NelsonMandelaBay EasternCape
30 NelsonMandelaBay NelsonMandelaBay EasternCape
31 NelsonMandelaBay NelsonMandelaBay EasternCape
32 NelsonMandelaBay NelsonMandelaBay EasternCape
33 NelsonMandelaBay NelsonMandelaBay EasternCape
34 NelsonMandelaBay NelsonMandelaBay EasternCape
35 NelsonMandelaBay NelsonMandelaBay EasternCape
36 NelsonMandelaBay NelsonMandelaBay EasternCape
37 NelsonMandelaBay NelsonMandelaBay EasternCape
38 NelsonMandelaBay NelsonMandelaBay EasternCape
39 NelsonMandelaBay NelsonMandelaBay EasternCape
4 NelsonMandelaBay NelsonMandelaBay EasternCape
40 NelsonMandelaBay NelsonMandelaBay EasternCape
41 NelsonMandelaBay NelsonMandelaBay EasternCape
42 NelsonMandelaBay NelsonMandelaBay EasternCape
43 NelsonMandelaBay NelsonMandelaBay EasternCape
44 NelsonMandelaBay NelsonMandelaBay EasternCape
45 NelsonMandelaBay NelsonMandelaBay EasternCape
46 NelsonMandelaBay NelsonMandelaBay EasternCape
47 NelsonMandelaBay NelsonMandelaBay EasternCape
48 NelsonMandelaBay NelsonMandelaBay EasternCape
49 NelsonMandelaBay NelsonMandelaBay EasternCape
5 NelsonMandelaBay NelsonMandelaBay EasternCape
50 NelsonMandelaBay NelsonMandelaBay EasternCape
51 NelsonMandelaBay NelsonMandelaBay EasternCape
52 NelsonMandelaBay NelsonMandelaBay EasternCape
53 NelsonMandelaBay NelsonMandelaBay EasternCape
54 NelsonMandelaBay NelsonMandelaBay EasternCape
55 NelsonMandelaBay NelsonMandelaBay EasternCape
56 NelsonMandelaBay NelsonMandelaBay EasternCape
57 NelsonMandelaBay NelsonMandelaBay EasternCape
58 NelsonMandelaBay NelsonMandelaBay EasternCape
59 NelsonMandelaBay NelsonMandelaBay EasternCape
6 NelsonMandelaBay NelsonMandelaBay EasternCape
60 NelsonMandelaBay NelsonMandelaBay EasternCape
7 NelsonMandelaBay NelsonMandelaBay EasternCape
8 NelsonMandelaBay NelsonMandelaBay EasternCape

In [60]:
df_colors = pd.DataFrame({"adm2_name": munis, "color": colors})
df_colors

              adm2_name  color
0  City of Johannesburg     25
1       City of Tshwane      0
2            Ekurhuleni      0
3             West Rand      0
4              Sedibeng      0

In [61]:
geo_df = gpd.GeoDataFrame.from_features(
    test["features"]
).merge(df_colors, on="adm2_name").set_index("adm2_name")

fig = px.choropleth(geo_df,
                   geojson=geo_df.geometry,
                   locations=geo_df.index,
                   color="color",
                   projection="mercator")
fig.update_geos(fitbounds="locations", visible=False)
fig.show(renderer="browser")

In [73]:
gdf = gpd.read_file("../data/raw/gadm41_ZAF_2.json")

In [74]:
gauteng = gdf[gdf["NAME_1"] == "Gauteng"].copy()

print(gauteng["NAME_2"].unique())
print(len(gauteng))

['CityofJohannesburg' 'CityofTshwane' 'Ekurhuleni' 'Sedibeng' 'WestRand']
5

In [75]:
gauteng_dissolved = (
    gauteng
    .dissolve(by="NAME_2", as_index=False)
)

print(gauteng_dissolved[["NAME_2"]])
print(len(gauteng_dissolved))

               NAME_2
0  CityofJohannesburg
1       CityofTshwane
2          Ekurhuleni
3            Sedibeng
4            WestRand
5

In [76]:
gauteng_dissolved["muni_id"] = range(len(gauteng_dissolved))

In [78]:
output_path = "../data/processed/gauteng_municipalities_clean.geojson"

gauteng_dissolved.to_file(
    output_path,
    driver="GeoJSON"
)

print("Saved:", output_path)

Saved: ../data/processed/gauteng_municipalities_clean.geojson

In [ ]:
import json
with open("../data/processed/gauteng_municipalities_clean.geojson") as f:
    gauteng_geojson = json.load(f)

df = pd.DataFrame({
    "name": ["City of Johannesburg", "City of Tshwane", "Ekurhuleni", "Sedibeng", "West Rand"],
    "muni_id": [0, 1, 2, 3, 4],
    "value": [8.2, 11.7, 10.4, 6.9, 9.6]
})

In [8]:
ids = [
    f["properties"]["muni_id"]
    for f in gauteng_geojson["features"]
]

assert len(ids) == len(set(ids)), "Duplicate IDs found!"

In [9]:
fig = px.choropleth(
    df,
    geojson=gauteng_geojson,
    locations="muni_id",
    featureidkey="properties.muni_id",
    color="value",
    color_continuous_scale="Viridis",
    projection='mercator',
    hover_name="name",
    hover_data='value'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.show(renderer="browser")

In [101]:
gdf4 = gpd.read_file("../data/raw/gadm41_ZAF_4.json")

In [102]:
tshwane = gdf4[gdf4["NAME_2"] == "CityofTshwane"].copy()

print(tshwane["NAME_4"].unique())
print(len(tshwane))

['1' '10' '100' '101' '102' '103' '104' '105' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '2' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '3' '30' '31' '32' '33' '34' '35' '36' '37' '38' '39' '4' '40' '41' '42'
 '43' '44' '45' '46' '47' '48' '49' '5' '50' '51' '52' '53' '54' '55' '56'
 '57' '58' '59' '6' '60' '61' '62' '63' '64' '65' '66' '67' '68' '69' '7'
 '70' '71' '72' '73' '74' '75' '76' '77' '78' '79' '8' '80' '81' '82' '83'
 '84' '85' '86' '87' '88' '89' '9' '90' '91' '92' '93' '94' '95' '96' '97'
 '98' '99']
105

In [103]:
tshwane_dissolved = (
    tshwane
    .dissolve(by="NAME_4", as_index=False)
)

print(tshwane_dissolved[["NAME_4"]])
print(len(tshwane_dissolved))

    NAME_4
0        1
1       10
2      100
3      101
4      102
..     ...
100     95
101     96
102     97
103     98
104     99

[105 rows x 1 columns]
105

In [104]:
output4_path = "../data/processed/tshwane_clean.geojson"

tshwane_dissolved.to_file(
    output4_path,
    driver="GeoJSON"
)

print("Saved:", output4_path)

Saved: ../data/processed/tshwane_clean.geojson

In [110]:
np.random.seed(42)
yield_df = pd.DataFrame({
    "NAME_4": tshwane["NAME_4"].unique(),
    "value": np.random.uniform(6, 12, 105)  # test data
})

with open("../data/processed/tshwane_clean.geojson") as f:
    tshwane_geojson = json.load(f)

In [111]:
tshwane_geojson

{'type': 'FeatureCollection',
 'name': 'tshwane_clean',
 'crs': {'type': 'name',
  'properties': {'name': 'urn:ogc:def:crs:OGC:1.3:CRS84'}},
 'features': [{'type': 'Feature',
   'properties': {'NAME_4': '1',
    'GID_4': 'ZAF.3.2.1.1_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900001'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.1498, -25.6925],
      [28.1595, -25.6935],
      [28.1596, -25.6921],
      [28.1812, -25.6942],
      [28.1819, -25.6957],
      [28.1864, -25.6933],
      [28.1863, -25.6984],
      [28.1848, -25.6983],
      [28.1842, -25.7028],
      [28.1819, -25.7029],
      [28.18, -25.7136],
      [28.1844, -25.7141],
      [28.1856, -25.7155],
      [28.186, -25.7128],
      [28.1933, -25.7135],
      [28.1933, -25.7148],
      [28.1987, -25.714],
      [28.2025, -25.7187],
      [28.2033, -25.7232],
      [28.1763, -25.7234],
      [28.1712, -25.7222],
      [28.1724, -25.7252],
      [28.1691, -25.7308],
      [28.1492, -25.7304],
      [28.1504, -25.7222],
      [28.148, -25.7219],
      [28.1486, -25.7183],
      [28.1408, -25.7179],
      [28.1431, -25.7038],
      [28.1487, -25.704],
      [28.1478, -25.7022],
      [28.1498, -25.6925]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '10',
    'GID_4': 'ZAF.3.2.1.2_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900010'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.4452, -25.7346],
      [28.4329, -25.7362],
      [28.4274, -25.7349],
      [28.4232, -25.7329],
      [28.4207, -25.7235],
      [28.4351, -25.7181],
      [28.4345, -25.7118],
      [28.4431, -25.708],
      [28.4452, -25.7346]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '100',
    'GID_4': 'ZAF.3.2.1.3_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900100'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.4232, -25.7329],
      [28.4316, -25.7362],
      [28.4405, -25.7343],
      [28.4516, -25.7352],
      [28.474, -25.7302],
      [28.476, -25.7305],
      [28.4761, -25.7352],
      [28.4919, -25.74],
      [28.4947, -25.7384],
      [28.4969, -25.7416],
      [28.5121, -25.7461],
      [28.5142, -25.7439],
      [28.5168, -25.7445],
      [28.5291, -25.7253],
      [28.5322, -25.7244],
      [28.5326, -25.7054],
      [28.5309, -25.7017],
      [28.5313, -25.6944],
      [28.5001, -25.691],
      [28.4817, -25.6727],
      [28.501, -25.6359],
      [28.5197, -25.6296],
      [28.5216, -25.6304],
      [28.5175, -25.6386],
      [28.5235, -25.6415],
      [28.5272, -25.636],
      [28.5289, -25.6367],
      [28.527, -25.6354],
      [28.5275, -25.6341],
      [28.529, -25.6348],
      [28.5297, -25.6334],
      [28.5468, -25.6408],
      [28.5653, -25.6431],
      [28.5633, -25.6378],
      [28.5668, -25.6352],
      [28.5671, -25.6263],
      [28.566, -25.6236],
      [28.5608, -25.6221],
      [28.5629, -25.6204],
      [28.5612, -25.6084],
      [28.5634, -25.597],
      [28.5678, -25.5885],
      [28.5684, -25.5832],
      [28.577, -25.5751],
      [28.5742, -25.5739],
      [28.5742, -25.5714],
      [28.5306, -25.5707],
      [28.5296, -25.5621],
      [28.5397, -25.5492],
      [28.5717, -25.5382],
      [28.6009, -25.5325],
      [28.6257, -25.5231],
      [28.6267, -25.5312],
      [28.635, -25.5592],
      [28.6455, -25.5858],
      [28.6473, -25.5856],
      [28.6425, -25.5899],
      [28.6747, -25.6588],
      [28.6351, -25.6709],
      [28.6503, -25.7055],
      [28.636, -25.7118],
      [28.6235, -25.7247],
      [28.6192, -25.7216],
      [28.6084, -25.7491],
      [28.5858, -25.7591],
      [28.5633, -25.7985],
      [28.534, -25.7984],
      [28.5151, -25.796],
      [28.5107, -25.7976],
      [28.5032, -25.7973],
      [28.4728, -25.7792],
      [28.4122, -25.7697],
      [28.4145, -25.7601],
      [28.4168, -25.7608],
      [28.4198, -25.7542],
      [28.4084, -25.7304],
      [28.4232, -25.7329]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '101',
    'GID_4': 'ZAF.3.2.1.4_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900101'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.4198, -25.7542],
      [28.4168, -25.7608],
      [28.4145, -25.7601],
      [28.4122, -25.7697],
      [28.4728, -25.7792],
      [28.5032, -25.7973],
      [28.5107, -25.7976],
      [28.5151, -25.796],
      [28.534, -25.7984],
      [28.5496, -25.7983],
      [28.5416, -25.8499],
      [28.5827, -25.867],
      [28.5753, -25.8987],
      [28.5983, -25.8953],
      [28.6276, -25.904],
      [28.6245, -25.9592],
      [28.6323, -25.9708],
      [28.591, -26.0025],
      [28.5867, -26.016],
      [28.5789, -26.0596],
      [28.5386, -26.0478],
      [28.5308, -26.0616],
      [28.5158, -26.0585],
      [28.4687, -26.0781],
      [28.4405, -26.0477],
      [28.4422, -26.0422],
      [28.4491, -26.0427],
      [28.4547, -26.0308],
      [28.4601, -26.0237],
      [28.4643, -26.0256],
      [28.4644, -26.0114],
      [28.4457, -26.0181],
      [28.4482, -25.9999],
      [28.4511, -25.9955],
      [28.4444, -25.9911],
      [28.4517, -25.9864],
      [28.4627, -25.9744],
      [28.468, -25.9633],
      [28.457, -25.9567],
      [28.446, -25.9649],
      [28.4177, -25.9505],
      [28.4167, -25.9484],
      [28.4195, -25.9487],
      [28.4176, -25.9394],
      [28.4096, -25.9275],
      [28.4161, -25.9203],
      [28.4019, -25.9044],
      [28.385, -25.8918],
      [28.3705, -25.8706],
      [28.4208, -25.8495],
      [28.385, -25.7959],
      [28.3386, -25.8162],
      [28.3222, -25.8024],
      [28.3381, -25.7918],
      [28.3775, -25.7392],
      [28.4198, -25.7542]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '102',
    'GID_4': 'ZAF.3.2.1.5_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900102'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.5496, -25.7983],
      [28.5633, -25.7985],
      [28.5858, -25.7591],
      [28.6084, -25.7491],
      [28.6192, -25.7216],
      [28.6235, -25.7247],
      [28.636, -25.7118],
      [28.6624, -25.7001],
      [28.6784, -25.7048],
      [28.6765, -25.7093],
      [28.6808, -25.7089],
      [28.6929, -25.7125],
      [28.7029, -25.7202],
      [28.7003, -25.7356],
      [28.7057, -25.7388],
      [28.7101, -25.7466],
      [28.7312, -25.7695],
      [28.741, -25.7696],
      [28.7443, -25.7792],
      [28.747, -25.7812],
      [28.7531, -25.7761],
      [28.757, -25.7789],
      [28.7551, -25.7813],
      [28.7595, -25.7871],
      [28.7589, -25.7888],
      [28.7507, -25.7884],
      [28.7498, -25.7919],
      [28.7512, -25.7948],
      [28.7341, -25.795],
      [28.7356, -25.81],
      [28.7302, -25.8112],
      [28.7218, -25.8104],
      [28.7208, -25.818],
      [28.7235, -25.8226],
      [28.7194, -25.8257],
      [28.7201, -25.8289],
      [28.7412, -25.8278],
      [28.7457, -25.8294],
      [28.7332, -25.8644],
      [28.7398, -25.8664],
      [28.7453, -25.8922],
      [28.7325, -25.9063],
      [28.7254, -25.9025],
      [28.7224, -25.9049],
      [28.7103, -25.9029],
      [28.7104, -25.9067],
      [28.7052, -25.9073],
      [28.6965, -25.9131],
      [28.704, -25.9311],
      [28.7007, -25.9324],
      [28.703, -25.9369],
      [28.7025, -25.9406],
      [28.7004, -25.9415],
      [28.6945, -25.9359],
      [28.6923, -25.9374],
      [28.6942, -25.9411],
      [28.6917, -25.9534],
      [28.6838, -25.9493],
      [28.684, -25.9381],
      [28.6891, -25.9243],
      [28.6891, -25.9208],
      [28.6831, -25.9137],
      [28.683, -25.9059],
      [28.6746, -25.9101],
      [28.6688, -25.9154],
      [28.6651, -25.9128],
      [28.6512, -25.9159],
      [28.6501, -25.9111],
      [28.6628, -25.9055],
      [28.663, -25.8897],
      [28.6457, -25.8854],
      [28.6312, -25.8779],
      [28.6332, -25.8878],
      [28.6276, -25.904],
      [28.5983, -25.8953],
      [28.5753, -25.8987],
      [28.5827, -25.867],
      [28.5416, -25.8499],
      [28.5496, -25.7983]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '103',
    'GID_4': 'ZAF.3.2.1.6_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900103'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.6503, -25.7055],
      [28.6351, -25.6709],
      [28.6747, -25.6588],
      [28.6727, -25.665],
      [28.6838, -25.6754],
      [28.7167, -25.6855],
      [28.7209, -25.676],
      [28.7266, -25.678],
      [28.7272, -25.683],
      [28.7304, -25.6836],
      [28.734, -25.679],
      [28.7367, -25.6792],
      [28.7379, -25.6735],
      [28.7524, -25.6795],
      [28.7591, -25.6777],
      [28.7529, -25.6937],
      [28.7474, -25.6921],
      [28.7463, -25.699],
      [28.7441, -25.699],
      [28.7397, -25.7104],
      [28.7515, -25.7155],
      [28.7513, -25.7182],
      [28.7476, -25.718],
      [28.7161, -25.732],
      [28.7106, -25.7472],
      [28.7057, -25.7388],
      [28.7003, -25.7356],
      [28.7029, -25.7202],
      [28.6965, -25.7143],
      [28.6814, -25.709],
      [28.6765, -25.7093],
      [28.6784, -25.7048],
      [28.6624, -25.7001],
      [28.6503, -25.7055]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '104',
    'GID_4': 'ZAF.3.2.1.7_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900104'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.7591, -25.6777],
      [28.7524, -25.6795],
      [28.7379, -25.6735],
      [28.7367, -25.6792],
      [28.734, -25.679],
      [28.7316, -25.6832],
      [28.7272, -25.683],
      [28.7268, -25.6782],
      [28.7209, -25.676],
      [28.7167, -25.6855],
      [28.7087, -25.6831],
      [28.7221, -25.6442],
      [28.7239, -25.6318],
      [28.7382, -25.6339],
      [28.7663, -25.647],
      [28.7591, -25.6777]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '105',
    'GID_4': 'ZAF.3.2.1.8_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900105'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.6323, -25.9708],
      [28.6245, -25.9592],
      [28.6274, -25.9043],
      [28.6332, -25.8878],
      [28.6312, -25.8779],
      [28.6457, -25.8854],
      [28.663, -25.8897],
      [28.6628, -25.9055],
      [28.6501, -25.9111],
      [28.6512, -25.9159],
      [28.6651, -25.9128],
      [28.6688, -25.9154],
      [28.6746, -25.9101],
      [28.683, -25.9059],
      [28.6831, -25.9137],
      [28.6891, -25.9208],
      [28.6891, -25.9243],
      [28.684, -25.9381],
      [28.6838, -25.9493],
      [28.6917, -25.9534],
      [28.6942, -25.9411],
      [28.6923, -25.9374],
      [28.6945, -25.9359],
      [28.7004, -25.9415],
      [28.7025, -25.9406],
      [28.703, -25.9369],
      [28.7007, -25.9324],
      [28.704, -25.9311],
      [28.6965, -25.9131],
      [28.7052, -25.9073],
      [28.7104, -25.9067],
      [28.7103, -25.9029],
      [28.7224, -25.9049],
      [28.7254, -25.9025],
      [28.7325, -25.9063],
      [28.7453, -25.8922],
      [28.7398, -25.8664],
      [28.7332, -25.8644],
      [28.7457, -25.8294],
      [28.7412, -25.8278],
      [28.7201, -25.8289],
      [28.7194, -25.8257],
      [28.7235, -25.8226],
      [28.7208, -25.818],
      [28.7218, -25.8104],
      [28.7302, -25.8112],
      [28.7356, -25.81],
      [28.7341, -25.795],
      [28.7512, -25.7948],
      [28.7498, -25.7919],
      [28.7507, -25.7884],
      [28.7589, -25.7888],
      [28.7595, -25.7871],
      [28.7551, -25.7813],
      [28.757, -25.7794],
      [28.7559, -25.7775],
      [28.7531, -25.7761],
      [28.747, -25.7812],
      [28.7443, -25.7792],
      [28.741, -25.7696],
      [28.7312, -25.7695],
      [28.7106, -25.7472],
      [28.7161, -25.732],
      [28.7476, -25.718],
      [28.7513, -25.7182],
      [28.7515, -25.7155],
      [28.7397, -25.7104],
      [28.7441, -25.699],
      [28.7463, -25.699],
      [28.7474, -25.6921],
      [28.7574, -25.6953],
      [28.7572, -25.7059],
      [28.7649, -25.7036],
      [28.7653, -25.7006],
      [28.7681, -25.7009],
      [28.7693, -25.6988],
      [28.7793, -25.7019],
      [28.7927, -25.7024],
      [28.8082, -25.689],
      [28.8193, -25.6951],
      [28.847, -25.6824],
      [28.8229, -25.6589],
      [28.81, -25.6591],
      [28.8115, -25.643],
      [28.836, -25.6374],
      [28.8355, -25.6456],
      [28.8416, -25.6545],
      [28.8457, -25.6523],
      [28.8693, -25.6581],
      [28.872, -25.6416],
      [28.8629, -25.6355],
      [28.8584, -25.6348],
      [28.8431, -25.5664],
      [28.8085, -25.5732],
      [28.7971, -25.542],
      [28.8219, -25.5224],
      [28.8518, -25.5018],
      [28.8699, -25.5247],
      [28.8741, -25.5271],
      [28.8582, -25.5691],
      [28.9101, -25.5245],
      [28.9152, -25.558],
      [28.9465, -25.5998],
      [29.0078, -25.5742],
      [28.9869, -25.5402],
      [28.9881, -25.5395],
      [28.9932, -25.5425],
      [29.0067, -25.5376],
      [29.0106, -25.5332],
      [29.019, -25.5278],
      [29.0129, -25.5137],
      [29.023, -25.5159],
      [29.036, -25.5213],
      [29.0422, -25.521],
      [29.0474, -25.517],
      [29.0482, -25.5202],
      [29.0587, -25.5272],
      [29.0787, -25.4996],
      [29.0774, -25.4962],
      [29.08, -25.4946],
      [29.0914, -25.5306],
      [29.0984, -25.5377],
      [29.0869, -25.5486],
      [29.0684, -25.5523],
      [29.0343, -25.5634],
      [29.042, -25.5733],
      [29.0456, -25.5808],
      [29.04, -25.6175],
      [29.0642, -25.6207],
      [29.0661, -25.6305],
      [29.0565, -25.6326],
      [29.0646, -25.6424],
      [28.9688, -25.6733],
      [28.9507, -25.7283],
      [28.9813, -25.7425],
      [28.9576, -25.7746],
      [28.9382, -25.8233],
      [28.9433, -25.8244],
      [28.9504, -25.8374],
      [28.9382, -25.8886],
      [28.8868, -25.8714],
      [28.8839, -25.8783],
      [28.889, -25.8803],
      [28.8795, -25.9252],
      [28.8825, -25.9698],
      [28.8833, -25.9714],
      [28.8852, -25.9714],
      [28.885, -25.9744],
      [28.8673, -26.007],
      [28.8648, -26.0013],
      [28.8329, -26.0048],
      [28.7939, -26.0046],
      [28.7739, -26.0137],
      [28.7624, -25.9831],
      [28.7579, -25.9837],
      [28.7575, -25.9906],
      [28.7108, -25.9906],
      [28.6527, -25.9743],
      [28.6323, -25.9708]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '11',
    'GID_4': 'ZAF.3.2.1.9_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900011'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.074, -25.441],
      [28.0923, -25.4382],
      [28.091, -25.4411],
      [28.092, -25.4424],
      [28.0892, -25.445],
      [28.0952, -25.4493],
      [28.0917, -25.455],
      [28.088, -25.4538],
      [28.0848, -25.4556],
      [28.0863, -25.4601],
      [28.0891, -25.4592],
      [28.09, -25.4624],
      [28.0866, -25.4639],
      [28.0877, -25.4696],
      [28.0916, -25.4737],
      [28.0896, -25.4785],
      [28.0831, -25.4687],
      [28.0794, -25.4688],
      [28.074, -25.441]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '12',
    'GID_4': 'ZAF.3.2.1.10_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900012'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.0456, -25.4949],
      [28.0474, -25.4887],
      [28.0555, -25.489],
      [28.0564, -25.4948],
      [28.0639, -25.4945],
      [28.0638, -25.4971],
      [28.0661, -25.4976],
      [28.0831, -25.4941],
      [28.09, -25.4952],
      [28.0839, -25.5169],
      [28.0798, -25.5101],
      [28.0766, -25.511],
      [28.0751, -25.5063],
      [28.0736, -25.5077],
      [28.0659, -25.5056],
      [28.0669, -25.5024],
      [28.0634, -25.5015],
      [28.0589, -25.5031],
      [28.0567, -25.5011],
      [28.0541, -25.5034],
      [28.0479, -25.4998],
      [28.0439, -25.5002],
      [28.0456, -25.4949]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '13',
    'GID_4': 'ZAF.3.2.1.11_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',
    'CC_4': '79900013'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[28.0923, -25.4382],
      [28.074, -25.441],
      [28.0673, -25.4195],
      [28.0555, -25.4],
      [28.0834, -25.3848],
      [28.108, -25.367],
      [28.1107, -25.3789],
      [28.1767, -25.3659],
      [28.1776, -25.3643],
      [28.1858, -25.375],
      [28.1825, -25.3755],
      [28.184, -25.3793],
      [28.183, -25.3814],
      [28.1846, -25.391],
      [28.2029, -25.3923],
      [28.2011, -25.4129],
      [28.1879, -25.4116],
      [28.1842, -25.4009],
      [28.1804, -25.4009],
      [28.1806, -25.3982],
      [28.178, -25.3974],
      [28.173, -25.3985],
      [28.173, -25.4027],
      [28.1695, -25.4049],
      [28.1706, -25.4078],
      [28.1594, -25.4087],
      [28.1588, -25.4041],
      [28.1507, -25.4044],
      [28.1505, -25.402],
      [28.1481, -25.4012],
      [28.1497, -25.397],
      [28.1469, -25.3957],
      [28.1209, -25.4003],
      [28.1162, -25.4034],
      [28.1235, -25.435],
      [28.1061, -25.4379],
      [28.1058, -25.4362],
      [28.0923, -25.4382]]]}},
  {'type': 'Feature',
   'properties': {'NAME_4': '14',
    'GID_4': 'ZAF.3.2.1.12_1',
    'GID_0': 'ZAF',
    'COUNTRY': 'SouthAfrica',
    'GID_1': 'ZAF.3_1',
    'NAME_1': 'Gauteng',
    'GID_2': 'ZAF.3.2_1',
    'NAME_2': 'CityofTshwane',
    'GID_3': 'ZAF.3.2.1_1',
    'NAME_3': 'CityofTshwane',
    'VARNAME_4': 'NA',
    'TYPE_4': 'Ward',
    'ENGTYPE_4': 'Ward',

In [113]:
ids = [
    f["properties"]["NAME_4"]
    for f in tshwane_geojson["features"]
]

assert len(ids) == len(set(ids)), "Duplicate IDs found!"

In [114]:
fig = px.choropleth(
    yield_df,
    geojson=tshwane_geojson,
    locations="NAME_4",
    featureidkey="properties.NAME_4",
    color="value",
    color_continuous_scale="Viridis",
    projection='mercator',
)

fig.update_geos(fitbounds="locations", visible=False)
fig.show(renderer="browser")

In [116]:
import osmnx as ox
import geopandas as gpd

gauteng = ox.geocode_to_gdf("Gauteng, South Africa")

suburbs = ox.features_from_place(
    "Gauteng, South Africa",
    tags={"place": ["suburb", "neighbourhood"]}
)

suburbs = suburbs.to_crs(epsg=4326)

In [118]:
suburbs.head()[["name", "place", "geometry"]]

                             name   place                    geometry
element id
node    25456068    Lynnwood Park  suburb  POINT (28.29333 -25.77694)
        25456193      Faerie Glen  suburb  POINT (28.30778 -25.78167)
        25456661      Garsfontein  suburb      POINT (28.3 -25.79444)
        25456662  Constantia Park  suburb  POINT (28.28222 -25.80806)
        25456663   Moreleta Kloof  suburb   POINT (28.2898 -25.81399)

In [ ]:
suburbs = suburbs[suburbs.geometry.type.isin(["Polygon", "MultiPolygon"])]
suburbs = suburbs[~suburbs["name"].isna()]

suburbs["suburb_name"] = suburbs["name"].str.lower().str.strip()
suburbs = suburbs[["suburb_name", "geometry"]]
suburbs = suburbs.dissolve(by="suburb_name", as_index=False)

,suburb_name,geometry
0,allen's nek,"POLYGON ((27.91017 -26.12839, 27.91527 -26.122..."
1,bedworth park,"POLYGON ((27.8886 -26.69856, 27.88907 -26.6995..."
2,boardwalk meander estate,"POLYGON ((28.33036 -25.80365, 28.33391 -25.806..."
3,boipatong,"POLYGON ((27.83742 -26.67398, 27.83741 -26.673..."
4,bonaero park,"POLYGON ((28.24906 -26.11613, 28.2511 -26.1151..."
...,...,...
60,villieria,"POLYGON ((28.24049 -25.69428, 28.24272 -25.695..."
61,waverley,"POLYGON ((28.06958 -26.13615, 28.06913 -26.137..."
62,weltevredenpark,"POLYGON ((27.95159 -26.11639, 27.9319 -26.1050..."
63,wilgeheuwel,"POLYGON ((27.90084 -26.12056, 27.89837 -26.118..."
64,wingate park,"POLYGON ((28.2722 -25.83992, 28.26759 -25.8337..."

In [ ]:
suburbs

In [127]:
output_path = "../data/processed/suburbs.geojson"

suburbs.to_file(
    output_path,
    driver="GeoJSON"
)

print("Saved:", output_path)

Saved: ../data/processed/suburbs.geojson

In [128]:
np.random.seed(42)
df = pd.DataFrame({
    "suburb_name": suburbs["suburb_name"].unique(),
    "value": np.random.uniform(6, 12, 65)  # test data
})

with open("../data/processed/suburbs.geojson") as f:
    suburbs_geojson = json.load(f)

In [129]:
fig = px.choropleth(
    df,
    geojson=suburbs_geojson,
    locations="suburb_name",
    featureidkey="properties.suburb_name",
    color="value",
    color_continuous_scale="Viridis",
    projection='mercator',
)

fig.update_geos(fitbounds="locations", visible=False)
fig.show(renderer="browser")

In [ ]:
places_search = ox.features_from_place(
    "Gauteng, South Africa",
    tags={"place": ["city", "town"]}
)

places = places_search.to_crs(epsg=4326)

In [134]:
places = places[
    places.geometry.type.isin(["Polygon", "MultiPolygon"])
]

places = places[~places["name"].isna()]

places["place_name"] = (
    places["name"]
    .str.lower()
    .str.strip()
)

places = places[["place_name", "place", "geometry"]]

places = places.dissolve(by="place_name", as_index=False)

In [137]:
target_cities = [
    "akasia","alberton","bedfordview","benoni","boksburg","brakpan",
    "bronkhorstspruit","carletonville","centurion","cullinan",
    "edenvale","eikenhof","evaton","fochville","ga-rankuwa",
    "germiston","hammanskraal","heidelberg","johannesburg",
    "katlehong","kempton park","krugersdorp","mabopane","meyerton",
    "midrand","nigel","pretoria","randburg","randfontein","rayton",
    "roodepoort","sandton","sebokeng","soshanguve","soweto","springs",
    "temba","tembisa","vaal marina","vanderbijlpark","vereeniging",
    "walkerville","westonaria","wonderboom"
]

cities = places[places["place_name"].isin(target_cities)]
cities

Empty GeoDataFrame
Columns: [place_name, geometry, place]
Index: []

In [1]:
cities = [
    "Pretoria, Gauteng, South Africa",
    "Johannesburg, Gauteng, South Africa",
    "Sandton, Gauteng, South Africa",
    "Centurion, Gauteng, South Africa",
    "Midrand, Gauteng, South Africa",
    "Randburg, Gauteng, South Africa",
    "Roodepoort, Gauteng, South Africa",
    "Soweto, Gauteng, South Africa",
    "Benoni, Gauteng, South Africa",
    "Boksburg, Gauteng, South Africa",
    "Kempton Park, Gauteng, South Africa",
    "Germiston, Gauteng, South Africa",
    "Alberton, Gauteng, South Africa",
    "Springs, Gauteng, South Africa",
    "Krugersdorp, Gauteng, South Africa",
    "Vereeniging, Gauteng, South Africa",
    "Vanderbijlpark, Gauteng, South Africa",
]

In [ ]:
pretoria = ox.f

In [5]:
gdfs = []

for city in cities:
    try:
        gdf = ox.geocode_to_gdf(city)
        gdf["city"] = city.split(",")[0]
        gdfs.append(gdf)
    except Exception as e:
        print(f"Failed: {city} -> {e}")

Failed: Pretoria, Gauteng, South Africa -> Nominatim did not geocode query 'Pretoria, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Johannesburg, Gauteng, South Africa -> Nominatim did not geocode query 'Johannesburg, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Sandton, Gauteng, South Africa -> Nominatim did not geocode query 'Sandton, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Centurion, Gauteng, South Africa -> Nominatim did not geocode query 'Centurion, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Midrand, Gauteng, South Africa -> Nominatim did not geocode query 'Midrand, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Randburg, Gauteng, South Africa -> Nominatim did not geocode query 'Randburg, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Soweto, Gauteng, South Africa -> Nominatim did not geocode query 'Soweto, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Benoni, Gauteng, South Africa -> Nominatim did not geocode query 'Benoni, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Boksburg, Gauteng, South Africa -> Nominatim did not geocode query 'Boksburg, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Kempton Park, Gauteng, South Africa -> Nominatim did not geocode query 'Kempton Park, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Germiston, Gauteng, South Africa -> Nominatim did not geocode query 'Germiston, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Springs, Gauteng, South Africa -> Nominatim did not geocode query 'Springs, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Krugersdorp, Gauteng, South Africa -> Nominatim did not geocode query 'Krugersdorp, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Vereeniging, Gauteng, South Africa -> Nominatim did not geocode query 'Vereeniging, Gauteng, South Africa' to a geometry of type (Multi)Polygon.
Failed: Vanderbijlpark, Gauteng, South Africa -> Nominatim did not geocode query 'Vanderbijlpark, Gauteng, South Africa' to a geometry of type (Multi)Polygon.